# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # Accounts Model.
  class Accounts < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Account Id of the customer.
    # Optional, if AccountNumber is passed, else mandatory.
    # @return [Integer]
    attr_accessor :account_id

    # Account Number of the customer.
    # Optional, if AccountId is passed, else mandatory.
    # @return [String]
    attr_accessor :account_number

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_id'] = 'AccountId'
      @_hash['account_number'] = 'AccountNumber'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_id
        account_number
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_id
        account_number
      ]
    end

    def initialize(account_id = SKIP,
                   account_number = SKIP)
      @account_id = account_id unless account_id == SKIP
      @account_number = account_number unless account_number == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_id = hash.key?('AccountId') ? hash['AccountId'] : SKIP
      account_number = hash.key?('AccountNumber') ? hash['AccountNumber'] : SKIP

      # Create object from extracted values.
      Accounts.new(account_id,
                   account_number)
    end
  end
end
