# shell_data_reporting_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ShellDataReportingApIs
  # CardUsageSummaryResponse Model.
  class CardUsageSummaryResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[UsageSummary]]
    attr_accessor :usage_summary

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['usage_summary'] = 'UsageSummary'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        usage_summary
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(usage_summary = SKIP)
      @usage_summary = usage_summary unless usage_summary == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      usage_summary = nil
      unless hash['UsageSummary'].nil?
        usage_summary = []
        hash['UsageSummary'].each do |structure|
          usage_summary << (UsageSummary.from_hash(structure) if structure)
        end
      end

      usage_summary = SKIP unless hash.key?('UsageSummary')

      # Create object from extracted values.
      CardUsageSummaryResponse.new(usage_summary)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} usage_summary: #{@usage_summary}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} usage_summary: #{@usage_summary.inspect}>"
    end
  end
end
