# shell_data_reporting_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ShellDataReportingApIs
  # CardGroupRes Model.
  class CardGroupRes < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Unique identifier for the request. This will be played back in the
    # response from the request.
    # @return [String]
    attr_accessor :request_id

    # Status of the request
    # @return [String]
    attr_accessor :status

    # Status of the request
    # @return [Array[CardGroupResponseCardGroupsItems]]
    attr_accessor :data

    # Current Page
    # @return [Integer]
    attr_accessor :page

    # Total row count matched for the given input criteria
    # @return [Integer]
    attr_accessor :total_records

    # Calculated page count based on page size from the incoming API request and
    # total number of rows matched for the given input criteria. Return 1 if the
    # page size is -1 as all records are returned.
    # @return [Integer]
    attr_accessor :total_pages

    # Page Size – Number of records to show on current page.
    # @return [Integer]
    attr_accessor :page_size

    # A list of Warning entity. 
    # This entity will hold the details of the scheduled System Outages of any
    # dependent applications of this service.
    # Note: If there is no scheduled outage information available, in the
    # configuration in AMS, for this service, this parameter won’t be present in
    # output.
    # @return [Array[Warning]]
    attr_accessor :warnings

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['request_id'] = 'RequestId'
      @_hash['status'] = 'Status'
      @_hash['data'] = 'Data'
      @_hash['page'] = 'Page'
      @_hash['total_records'] = 'TotalRecords'
      @_hash['total_pages'] = 'TotalPages'
      @_hash['page_size'] = 'PageSize'
      @_hash['warnings'] = 'Warnings'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        request_id
        status
        data
        page
        total_records
        total_pages
        page_size
        warnings
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(request_id = SKIP, status = SKIP, data = SKIP, page = SKIP,
                   total_records = SKIP, total_pages = SKIP, page_size = SKIP,
                   warnings = SKIP)
      @request_id = request_id unless request_id == SKIP
      @status = status unless status == SKIP
      @data = data unless data == SKIP
      @page = page unless page == SKIP
      @total_records = total_records unless total_records == SKIP
      @total_pages = total_pages unless total_pages == SKIP
      @page_size = page_size unless page_size == SKIP
      @warnings = warnings unless warnings == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      request_id = hash.key?('RequestId') ? hash['RequestId'] : SKIP
      status = hash.key?('Status') ? hash['Status'] : SKIP
      # Parameter is an array, so we need to iterate through it
      data = nil
      unless hash['Data'].nil?
        data = []
        hash['Data'].each do |structure|
          data << (CardGroupResponseCardGroupsItems.from_hash(structure) if structure)
        end
      end

      data = SKIP unless hash.key?('Data')
      page = hash.key?('Page') ? hash['Page'] : SKIP
      total_records = hash.key?('TotalRecords') ? hash['TotalRecords'] : SKIP
      total_pages = hash.key?('TotalPages') ? hash['TotalPages'] : SKIP
      page_size = hash.key?('PageSize') ? hash['PageSize'] : SKIP
      # Parameter is an array, so we need to iterate through it
      warnings = nil
      unless hash['Warnings'].nil?
        warnings = []
        hash['Warnings'].each do |structure|
          warnings << (Warning.from_hash(structure) if structure)
        end
      end

      warnings = SKIP unless hash.key?('Warnings')

      # Create object from extracted values.
      CardGroupRes.new(request_id,
                       status,
                       data,
                       page,
                       total_records,
                       total_pages,
                       page_size,
                       warnings)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} request_id: #{@request_id}, status: #{@status}, data: #{@data}, page:"\
      " #{@page}, total_records: #{@total_records}, total_pages: #{@total_pages}, page_size:"\
      " #{@page_size}, warnings: #{@warnings}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} request_id: #{@request_id.inspect}, status: #{@status.inspect}, data:"\
      " #{@data.inspect}, page: #{@page.inspect}, total_records: #{@total_records.inspect},"\
      " total_pages: #{@total_pages.inspect}, page_size: #{@page_size.inspect}, warnings:"\
      " #{@warnings.inspect}>"
    end
  end
end
