# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # CardTypeResponse Model.
  class CardTypeResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[CardTypeResponseCustomerCardTypesItems]]
    attr_accessor :customer_card_types

    # TODO: Write general description for this method
    # @return [CardTypeResponseError]
    attr_accessor :error

    # API Request Id
    # @return [String]
    attr_accessor :request_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['customer_card_types'] = 'CustomerCardTypes'
      @_hash['error'] = 'Error'
      @_hash['request_id'] = 'RequestId'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        customer_card_types
        error
        request_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(customer_card_types = SKIP, error = SKIP, request_id = SKIP)
      @customer_card_types = customer_card_types unless customer_card_types == SKIP
      @error = error unless error == SKIP
      @request_id = request_id unless request_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      customer_card_types = nil
      unless hash['CustomerCardTypes'].nil?
        customer_card_types = []
        hash['CustomerCardTypes'].each do |structure|
          customer_card_types << (CardTypeResponseCustomerCardTypesItems.from_hash(structure) if structure)
        end
      end

      customer_card_types = SKIP unless hash.key?('CustomerCardTypes')
      error = CardTypeResponseError.from_hash(hash['Error']) if hash['Error']
      request_id = hash.key?('RequestId') ? hash['RequestId'] : SKIP

      # Create object from extracted values.
      CardTypeResponse.new(customer_card_types,
                           error,
                           request_id)
    end
  end
end
