# shell_data_reporting_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ShellDataReportingApIs
  # CustomerPriceListResponse Model.
  class CustomerPriceListResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[PriceList]]
    attr_accessor :price_list

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['price_list'] = 'PriceList'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        price_list
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(price_list = SKIP)
      @price_list = price_list unless price_list == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      price_list = nil
      unless hash['PriceList'].nil?
        price_list = []
        hash['PriceList'].each do |structure|
          price_list << (PriceList.from_hash(structure) if structure)
        end
      end

      price_list = SKIP unless hash.key?('PriceList')

      # Create object from extracted values.
      CustomerPriceListResponse.new(price_list)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} price_list: #{@price_list}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} price_list: #{@price_list.inspect}>"
    end
  end
end
