# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # FeeRuleProduct Model.
  class FeeRuleProduct < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Product Group Id
    # @return [Integer]
    attr_accessor :product_group_id

    # Product Group name
    # @return [String]
    attr_accessor :product_group_name

    # Client Product Code
    # @return [String]
    attr_accessor :product_code

    # Product Id
    # @return [Integer]
    attr_accessor :product_id

    # Product name in English
    # @return [String]
    attr_accessor :product_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['product_group_id'] = 'ProductGroupId'
      @_hash['product_group_name'] = 'ProductGroupName'
      @_hash['product_code'] = 'ProductCode'
      @_hash['product_id'] = 'ProductId'
      @_hash['product_name'] = 'ProductName'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        product_group_id
        product_group_name
        product_code
        product_id
        product_name
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        product_group_id
        product_group_name
        product_code
        product_id
        product_name
      ]
    end

    def initialize(product_group_id = SKIP, product_group_name = SKIP,
                   product_code = SKIP, product_id = SKIP, product_name = SKIP)
      @product_group_id = product_group_id unless product_group_id == SKIP
      @product_group_name = product_group_name unless product_group_name == SKIP
      @product_code = product_code unless product_code == SKIP
      @product_id = product_id unless product_id == SKIP
      @product_name = product_name unless product_name == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      product_group_id =
        hash.key?('ProductGroupId') ? hash['ProductGroupId'] : SKIP
      product_group_name =
        hash.key?('ProductGroupName') ? hash['ProductGroupName'] : SKIP
      product_code = hash.key?('ProductCode') ? hash['ProductCode'] : SKIP
      product_id = hash.key?('ProductId') ? hash['ProductId'] : SKIP
      product_name = hash.key?('ProductName') ? hash['ProductName'] : SKIP

      # Create object from extracted values.
      FeeRuleProduct.new(product_group_id,
                         product_group_name,
                         product_code,
                         product_id,
                         product_name)
    end
  end
end
