# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # FeeItem Model.
  class FeeItem < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Fee Item unique identifier in the H3 Cards Platform
    # @return [Integer]
    attr_accessor :fee_item_id

    # Account Id
    # @return [Integer]
    attr_accessor :account_id

    # Account Number
    # @return [String]
    attr_accessor :account_number

    # Account short Number
    # @return [String]
    attr_accessor :account_short_name

    # Invoice Account Id
    # @return [Integer]
    attr_accessor :invoice_account_id

    # Invoice Account Number
    # @return [String]
    attr_accessor :invoice_account_number

    # Invoice Account short Name
    # @return [String]
    attr_accessor :invoice_account_short_name

    # Payer Id
    # @return [Integer]
    attr_accessor :payer_id

    # Payer Number
    # @return [String]
    attr_accessor :payer_number

    # Payer short Name
    # @return [String]
    attr_accessor :payer_short_name

    # Unique Card Id
    # @return [Integer]
    attr_accessor :card_id

    # Card PAN
    # @return [String]
    attr_accessor :pan

    # Card Group Id
    # @return [Integer]
    attr_accessor :card_group_id

    # Card Group Name
    # @return [String]
    attr_accessor :card_group_name

    # Fee type identifier.
    # @return [Integer]
    attr_accessor :fee_type_id

    # Fee type description
    # @return [String]
    attr_accessor :fee_type

    # Fee type group in under which the Fee item is generated.
    # Example: 
    # Account
    # Card
    # Others
    # @return [String]
    attr_accessor :fee_type_group

    # Fee rule identifier
    # @return [Integer]
    attr_accessor :fee_rule_id

    # Fee rule description
    # @return [String]
    attr_accessor :fee_rule_description

    # Fee rule description
    # @return [Array[FeesFeeRuleTiers]]
    attr_accessor :fee_rule_tiers

    # Local Fee Item Date of when the transaction took place
    # Format: yyyyMMdd
    # @return [String]
    attr_accessor :fee_item_date

    # Local Fee Item Time of where the transaction took place
    # Format: HH:mm:ss (24 hours format)
    # @return [String]
    attr_accessor :fee_item_time

    # True/False.
    # Is manual
    # @return [TrueClass | FalseClass]
    attr_accessor :is_manual

    # True/False.
    # Is cancelled
    # @return [TrueClass | FalseClass]
    attr_accessor :is_cancelled

    # ISO currency code 
    # Example: GBP
    # @return [String]
    attr_accessor :customer_currency_code

    # Currency symbol of the Currency Code 
    # Example: £, $
    # @return [String]
    attr_accessor :customer_currency_symbol

    # Product Id
    # Example: Sample list of product ids and description.
    # 100 Service fee
    # 102 Invoice production fee
    # 103 Account fee
    # 104 Transaction fee
    # 105 Card membership fee
    # @return [Integer]
    attr_accessor :product_id

    # Product Code – Global as per GFN configuration 
    # Example: 
    # 2 Service fee
    # 4 Invoice production fee
    # 5 Account fee
    # 6 Transaction fee
    # 7 Card membership fee
    # @return [String]
    attr_accessor :product_code

    # Product Name
    # Example: Sample list of product ids and description.
    # Service fee
    # Invoice production fee
    # @return [String]
    attr_accessor :product_name

    # Product Group Id
    # Example: Sample list
    # 22    Card related fees
    # 23    Monetary Adjustment
    # @return [Integer]
    attr_accessor :product_group_id

    # Product Group Name
    # Example: Sample list
    # 22    Card related fees
    # 23    Monetary Adjustment
    # @return [String]
    attr_accessor :product_group_name

    # Line Item Description generally the quantity as printed on Invoice or the
    # manually keyed in description for manual fees
    # @return [String]
    attr_accessor :line_item_description

    # Quantity
    # @return [Integer]
    attr_accessor :quantity

    # True/False.
    # Is fee item invoiced
    # @return [TrueClass | FalseClass]
    attr_accessor :is_invoiced

    # VAT country ISO code
    # @return [String]
    attr_accessor :vat_country_code

    # VAT country name
    # @return [String]
    attr_accessor :vat_country_name

    # VAT percentage
    # @return [Float]
    attr_accessor :vat_percentage

    # VAT Category identifier
    # @return [Integer]
    attr_accessor :vat_category_id

    # VAT Category description
    # @return [String]
    attr_accessor :vat_category_description

    # Legislative region id
    # @return [Integer]
    attr_accessor :legislative_region_id

    # Legislative region name
    # @return [String]
    attr_accessor :legislative_region_name

    # System entry date
    # @return [String]
    attr_accessor :system_entry_date

    # System entry time
    # @return [String]
    attr_accessor :system_entry_time

    # ColCo net amount
    # @return [Float]
    attr_accessor :col_co_net_amount

    # ColCoVAT amount
    # @return [Float]
    attr_accessor :col_co_vat_amount

    # ColCo gross amount
    # @return [Float]
    attr_accessor :col_co_gross_amount

    # Interim invoice id
    # @return [Integer]
    attr_accessor :interim_invoice_id

    # Interim invoice number
    # @return [String]
    attr_accessor :interim_invoice_number

    # Invoice id
    # @return [Integer]
    attr_accessor :invoice_id

    # Invoice number
    # @return [String]
    attr_accessor :invoice_number

    # Invoice date 
    # Format: yyyyMMdd
    # @return [String]
    attr_accessor :invoice_date

    # Customer exchange rate
    # @return [Float]
    attr_accessor :customer_exchange_rate

    # Invoice net amount
    # @return [Float]
    attr_accessor :invoice_net_amount

    # Invoice gross amount
    # @return [Float]
    attr_accessor :invoice_gross_amount

    # Invoice VAT amount
    # @return [Float]
    attr_accessor :invoice_vat_amount

    # True/False.
    # Reverse charge.
    # @return [TrueClass | FalseClass]
    attr_accessor :reverse_charge

    # Original Fee Item id.
    # @return [Integer]
    attr_accessor :original_fee_item_id

    # Original FeeItem Currency ISO code.
    # @return [String]
    attr_accessor :original_currency_code

    # Original FeeItem currency symbol
    # @return [String]
    attr_accessor :original_currency_symbol

    # Original FeeItem unit price
    # @return [Float]
    attr_accessor :original_unit_price

    # Original FeeItem net amount
    # @return [Float]
    attr_accessor :original_net_amount

    # Original FeeItem VAT amount
    # @return [Float]
    attr_accessor :original_vat_amount

    # Original FeeItem gross amount
    # @return [Float]
    attr_accessor :original_gross_amount

    # Original FeeItem exchange rate
    # @return [Float]
    attr_accessor :original_exchange_rate

    # Original legislative region id
    # @return [Integer]
    attr_accessor :original_legislative_region_id

    # Original legislative region name
    # @return [String]
    attr_accessor :original_legislative_region_name

    # Fee frequency derived from Fee rules if applicable
    # Returns ID-Description in one field
    # Example: 
    # 1- Daily (all days)
    # 2-Daily (only working days)
    # 3-Weekly – Monday
    # 4-Weekly - Tuesday
    # @return [String]
    attr_accessor :frequency

    # Fee breakup at card level for Fee Items where applicable.
    # @return [String]
    attr_accessor :fee_item_card_level_breakup

    # Invoice Id/ Billing Document Id of the original fee item (when not null).
    # Applicable only for fee items that are refund to an original fee item that
    # is already invoiced.
    # @return [Integer]
    attr_accessor :original_fee_item_invoice_id

    # Invoice Number of the original fee item (when not null).
    # Applicable only for fee items that are refund to an original fee item that
    # is already invoiced.
    # @return [String]
    attr_accessor :original_fee_item_invoice_number

    # Invoice Date of the original fee item (when not null).
    # Applicable only for fee items that are refund to an original fee item that
    # is already invoiced.
    # Format: yyyyMMdd
    # @return [String]
    attr_accessor :original_fee_item_invoice_date

    # Driver name embossed on the Card
    # @return [String]
    attr_accessor :driver_name

    # Text embossed on the Card
    # @return [String]
    attr_accessor :emboss_text

    # Reg. Number embossed on the Card
    # @return [String]
    attr_accessor :vrn

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['fee_item_id'] = 'FeeItemId'
      @_hash['account_id'] = 'AccountId'
      @_hash['account_number'] = 'AccountNumber'
      @_hash['account_short_name'] = 'AccountShortName'
      @_hash['invoice_account_id'] = 'InvoiceAccountId'
      @_hash['invoice_account_number'] = 'InvoiceAccountNumber'
      @_hash['invoice_account_short_name'] = 'InvoiceAccountShortName'
      @_hash['payer_id'] = 'PayerId'
      @_hash['payer_number'] = 'PayerNumber'
      @_hash['payer_short_name'] = 'PayerShortName'
      @_hash['card_id'] = 'CardId'
      @_hash['pan'] = 'PAN'
      @_hash['card_group_id'] = 'CardGroupId'
      @_hash['card_group_name'] = 'CardGroupName'
      @_hash['fee_type_id'] = 'FeeTypeId'
      @_hash['fee_type'] = 'FeeType'
      @_hash['fee_type_group'] = 'FeeTypeGroup'
      @_hash['fee_rule_id'] = 'FeeRuleId'
      @_hash['fee_rule_description'] = 'FeeRuleDescription'
      @_hash['fee_rule_tiers'] = 'FeeRuleTiers'
      @_hash['fee_item_date'] = 'FeeItemDate'
      @_hash['fee_item_time'] = 'FeeItemTime'
      @_hash['is_manual'] = 'IsManual'
      @_hash['is_cancelled'] = 'IsCancelled'
      @_hash['customer_currency_code'] = 'CustomerCurrencyCode'
      @_hash['customer_currency_symbol'] = 'CustomerCurrencySymbol'
      @_hash['product_id'] = 'ProductId'
      @_hash['product_code'] = 'ProductCode'
      @_hash['product_name'] = 'ProductName'
      @_hash['product_group_id'] = 'ProductGroupId'
      @_hash['product_group_name'] = 'ProductGroupName'
      @_hash['line_item_description'] = 'LineItemDescription'
      @_hash['quantity'] = 'Quantity'
      @_hash['is_invoiced'] = 'IsInvoiced'
      @_hash['vat_country_code'] = 'VATCountryCode'
      @_hash['vat_country_name'] = 'VATCountryName'
      @_hash['vat_percentage'] = 'VATPercentage'
      @_hash['vat_category_id'] = 'VATCategoryID'
      @_hash['vat_category_description'] = 'VATCategoryDescription'
      @_hash['legislative_region_id'] = 'LegislativeRegionId'
      @_hash['legislative_region_name'] = 'LegislativeRegionName'
      @_hash['system_entry_date'] = 'SystemEntryDate'
      @_hash['system_entry_time'] = 'SystemEntryTime'
      @_hash['col_co_net_amount'] = 'ColCoNetAmount'
      @_hash['col_co_vat_amount'] = 'ColCoVATAmount'
      @_hash['col_co_gross_amount'] = 'ColCoGrossAmount'
      @_hash['interim_invoice_id'] = 'InterimInvoiceId'
      @_hash['interim_invoice_number'] = 'InterimInvoiceNumber'
      @_hash['invoice_id'] = 'InvoiceId'
      @_hash['invoice_number'] = 'InvoiceNumber'
      @_hash['invoice_date'] = 'InvoiceDate'
      @_hash['customer_exchange_rate'] = 'CustomerExchangeRate'
      @_hash['invoice_net_amount'] = 'InvoiceNetAmount'
      @_hash['invoice_gross_amount'] = 'InvoiceGrossAmount'
      @_hash['invoice_vat_amount'] = 'InvoiceVATAmount'
      @_hash['reverse_charge'] = 'ReverseCharge'
      @_hash['original_fee_item_id'] = 'OriginalFeeItemId'
      @_hash['original_currency_code'] = 'OriginalCurrencyCode'
      @_hash['original_currency_symbol'] = 'OriginalCurrencySymbol'
      @_hash['original_unit_price'] = 'OriginalUnitPrice'
      @_hash['original_net_amount'] = 'OriginalNetAmount'
      @_hash['original_vat_amount'] = 'OriginalVATAmount'
      @_hash['original_gross_amount'] = 'OriginalGrossAmount'
      @_hash['original_exchange_rate'] = 'OriginalExchangeRate'
      @_hash['original_legislative_region_id'] = 'OriginalLegislativeRegionId'
      @_hash['original_legislative_region_name'] =
        'OriginalLegislativeRegionName'
      @_hash['frequency'] = 'Frequency'
      @_hash['fee_item_card_level_breakup'] = 'FeeItemCardLevelBreakup'
      @_hash['original_fee_item_invoice_id'] = 'OriginalFeeItemInvoiceId'
      @_hash['original_fee_item_invoice_number'] =
        'OriginalFeeItemInvoiceNumber'
      @_hash['original_fee_item_invoice_date'] = 'OriginalFeeItemInvoiceDate'
      @_hash['driver_name'] = 'DriverName'
      @_hash['emboss_text'] = 'EmbossText'
      @_hash['vrn'] = 'VRN'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        fee_item_id
        account_id
        account_number
        account_short_name
        invoice_account_id
        invoice_account_number
        invoice_account_short_name
        payer_id
        payer_number
        payer_short_name
        card_id
        pan
        card_group_id
        card_group_name
        fee_type_id
        fee_type
        fee_type_group
        fee_rule_id
        fee_rule_description
        fee_rule_tiers
        fee_item_date
        fee_item_time
        is_manual
        is_cancelled
        customer_currency_code
        customer_currency_symbol
        product_id
        product_code
        product_name
        product_group_id
        product_group_name
        line_item_description
        quantity
        is_invoiced
        vat_country_code
        vat_country_name
        vat_percentage
        vat_category_id
        vat_category_description
        legislative_region_id
        legislative_region_name
        system_entry_date
        system_entry_time
        col_co_net_amount
        col_co_vat_amount
        col_co_gross_amount
        interim_invoice_id
        interim_invoice_number
        invoice_id
        invoice_number
        invoice_date
        customer_exchange_rate
        invoice_net_amount
        invoice_gross_amount
        invoice_vat_amount
        reverse_charge
        original_fee_item_id
        original_currency_code
        original_currency_symbol
        original_unit_price
        original_net_amount
        original_vat_amount
        original_gross_amount
        original_exchange_rate
        original_legislative_region_id
        original_legislative_region_name
        frequency
        fee_item_card_level_breakup
        original_fee_item_invoice_id
        original_fee_item_invoice_number
        original_fee_item_invoice_date
        driver_name
        emboss_text
        vrn
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        fee_item_id
        account_id
        account_number
        account_short_name
        invoice_account_id
        invoice_account_number
        invoice_account_short_name
        payer_id
        payer_number
        payer_short_name
        card_id
        pan
        card_group_id
        card_group_name
        fee_type_id
        fee_type
        fee_type_group
        fee_rule_id
        fee_rule_description
        fee_item_date
        fee_item_time
        is_manual
        is_cancelled
        customer_currency_code
        customer_currency_symbol
        product_id
        product_code
        product_name
        product_group_id
        product_group_name
        line_item_description
        quantity
        is_invoiced
        vat_country_code
        vat_country_name
        vat_percentage
        vat_category_id
        vat_category_description
        legislative_region_id
        legislative_region_name
        system_entry_date
        system_entry_time
        col_co_net_amount
        col_co_vat_amount
        col_co_gross_amount
        interim_invoice_id
        interim_invoice_number
        invoice_id
        invoice_number
        invoice_date
        customer_exchange_rate
        invoice_net_amount
        invoice_gross_amount
        invoice_vat_amount
        reverse_charge
        original_fee_item_id
        original_currency_code
        original_currency_symbol
        original_unit_price
        original_net_amount
        original_vat_amount
        original_gross_amount
        original_exchange_rate
        original_legislative_region_id
        original_legislative_region_name
        frequency
        fee_item_card_level_breakup
        original_fee_item_invoice_id
        original_fee_item_invoice_number
        original_fee_item_invoice_date
        driver_name
        emboss_text
        vrn
      ]
    end

    def initialize(fee_item_id = SKIP, account_id = SKIP, account_number = SKIP,
                   account_short_name = SKIP, invoice_account_id = SKIP,
                   invoice_account_number = SKIP,
                   invoice_account_short_name = SKIP, payer_id = SKIP,
                   payer_number = SKIP, payer_short_name = SKIP, card_id = SKIP,
                   pan = SKIP, card_group_id = SKIP, card_group_name = SKIP,
                   fee_type_id = SKIP, fee_type = SKIP, fee_type_group = SKIP,
                   fee_rule_id = SKIP, fee_rule_description = SKIP,
                   fee_rule_tiers = SKIP, fee_item_date = SKIP,
                   fee_item_time = SKIP, is_manual = SKIP, is_cancelled = SKIP,
                   customer_currency_code = SKIP,
                   customer_currency_symbol = SKIP, product_id = SKIP,
                   product_code = SKIP, product_name = SKIP,
                   product_group_id = SKIP, product_group_name = SKIP,
                   line_item_description = SKIP, quantity = SKIP,
                   is_invoiced = SKIP, vat_country_code = SKIP,
                   vat_country_name = SKIP, vat_percentage = SKIP,
                   vat_category_id = SKIP, vat_category_description = SKIP,
                   legislative_region_id = SKIP, legislative_region_name = SKIP,
                   system_entry_date = SKIP, system_entry_time = SKIP,
                   col_co_net_amount = SKIP, col_co_vat_amount = SKIP,
                   col_co_gross_amount = SKIP, interim_invoice_id = SKIP,
                   interim_invoice_number = SKIP, invoice_id = SKIP,
                   invoice_number = SKIP, invoice_date = SKIP,
                   customer_exchange_rate = SKIP, invoice_net_amount = SKIP,
                   invoice_gross_amount = SKIP, invoice_vat_amount = SKIP,
                   reverse_charge = SKIP, original_fee_item_id = SKIP,
                   original_currency_code = SKIP,
                   original_currency_symbol = SKIP, original_unit_price = SKIP,
                   original_net_amount = SKIP, original_vat_amount = SKIP,
                   original_gross_amount = SKIP, original_exchange_rate = SKIP,
                   original_legislative_region_id = SKIP,
                   original_legislative_region_name = SKIP, frequency = SKIP,
                   fee_item_card_level_breakup = SKIP,
                   original_fee_item_invoice_id = SKIP,
                   original_fee_item_invoice_number = SKIP,
                   original_fee_item_invoice_date = SKIP, driver_name = SKIP,
                   emboss_text = SKIP, vrn = SKIP)
      @fee_item_id = fee_item_id unless fee_item_id == SKIP
      @account_id = account_id unless account_id == SKIP
      @account_number = account_number unless account_number == SKIP
      @account_short_name = account_short_name unless account_short_name == SKIP
      @invoice_account_id = invoice_account_id unless invoice_account_id == SKIP
      @invoice_account_number = invoice_account_number unless invoice_account_number == SKIP
      unless invoice_account_short_name == SKIP
        @invoice_account_short_name =
          invoice_account_short_name
      end
      @payer_id = payer_id unless payer_id == SKIP
      @payer_number = payer_number unless payer_number == SKIP
      @payer_short_name = payer_short_name unless payer_short_name == SKIP
      @card_id = card_id unless card_id == SKIP
      @pan = pan unless pan == SKIP
      @card_group_id = card_group_id unless card_group_id == SKIP
      @card_group_name = card_group_name unless card_group_name == SKIP
      @fee_type_id = fee_type_id unless fee_type_id == SKIP
      @fee_type = fee_type unless fee_type == SKIP
      @fee_type_group = fee_type_group unless fee_type_group == SKIP
      @fee_rule_id = fee_rule_id unless fee_rule_id == SKIP
      @fee_rule_description = fee_rule_description unless fee_rule_description == SKIP
      @fee_rule_tiers = fee_rule_tiers unless fee_rule_tiers == SKIP
      @fee_item_date = fee_item_date unless fee_item_date == SKIP
      @fee_item_time = fee_item_time unless fee_item_time == SKIP
      @is_manual = is_manual unless is_manual == SKIP
      @is_cancelled = is_cancelled unless is_cancelled == SKIP
      @customer_currency_code = customer_currency_code unless customer_currency_code == SKIP
      @customer_currency_symbol = customer_currency_symbol unless customer_currency_symbol == SKIP
      @product_id = product_id unless product_id == SKIP
      @product_code = product_code unless product_code == SKIP
      @product_name = product_name unless product_name == SKIP
      @product_group_id = product_group_id unless product_group_id == SKIP
      @product_group_name = product_group_name unless product_group_name == SKIP
      @line_item_description = line_item_description unless line_item_description == SKIP
      @quantity = quantity unless quantity == SKIP
      @is_invoiced = is_invoiced unless is_invoiced == SKIP
      @vat_country_code = vat_country_code unless vat_country_code == SKIP
      @vat_country_name = vat_country_name unless vat_country_name == SKIP
      @vat_percentage = vat_percentage unless vat_percentage == SKIP
      @vat_category_id = vat_category_id unless vat_category_id == SKIP
      @vat_category_description = vat_category_description unless vat_category_description == SKIP
      @legislative_region_id = legislative_region_id unless legislative_region_id == SKIP
      @legislative_region_name = legislative_region_name unless legislative_region_name == SKIP
      @system_entry_date = system_entry_date unless system_entry_date == SKIP
      @system_entry_time = system_entry_time unless system_entry_time == SKIP
      @col_co_net_amount = col_co_net_amount unless col_co_net_amount == SKIP
      @col_co_vat_amount = col_co_vat_amount unless col_co_vat_amount == SKIP
      @col_co_gross_amount = col_co_gross_amount unless col_co_gross_amount == SKIP
      @interim_invoice_id = interim_invoice_id unless interim_invoice_id == SKIP
      @interim_invoice_number = interim_invoice_number unless interim_invoice_number == SKIP
      @invoice_id = invoice_id unless invoice_id == SKIP
      @invoice_number = invoice_number unless invoice_number == SKIP
      @invoice_date = invoice_date unless invoice_date == SKIP
      @customer_exchange_rate = customer_exchange_rate unless customer_exchange_rate == SKIP
      @invoice_net_amount = invoice_net_amount unless invoice_net_amount == SKIP
      @invoice_gross_amount = invoice_gross_amount unless invoice_gross_amount == SKIP
      @invoice_vat_amount = invoice_vat_amount unless invoice_vat_amount == SKIP
      @reverse_charge = reverse_charge unless reverse_charge == SKIP
      @original_fee_item_id = original_fee_item_id unless original_fee_item_id == SKIP
      @original_currency_code = original_currency_code unless original_currency_code == SKIP
      @original_currency_symbol = original_currency_symbol unless original_currency_symbol == SKIP
      @original_unit_price = original_unit_price unless original_unit_price == SKIP
      @original_net_amount = original_net_amount unless original_net_amount == SKIP
      @original_vat_amount = original_vat_amount unless original_vat_amount == SKIP
      @original_gross_amount = original_gross_amount unless original_gross_amount == SKIP
      @original_exchange_rate = original_exchange_rate unless original_exchange_rate == SKIP
      unless original_legislative_region_id == SKIP
        @original_legislative_region_id =
          original_legislative_region_id
      end
      unless original_legislative_region_name == SKIP
        @original_legislative_region_name =
          original_legislative_region_name
      end
      @frequency = frequency unless frequency == SKIP
      unless fee_item_card_level_breakup == SKIP
        @fee_item_card_level_breakup =
          fee_item_card_level_breakup
      end
      unless original_fee_item_invoice_id == SKIP
        @original_fee_item_invoice_id =
          original_fee_item_invoice_id
      end
      unless original_fee_item_invoice_number == SKIP
        @original_fee_item_invoice_number =
          original_fee_item_invoice_number
      end
      unless original_fee_item_invoice_date == SKIP
        @original_fee_item_invoice_date =
          original_fee_item_invoice_date
      end
      @driver_name = driver_name unless driver_name == SKIP
      @emboss_text = emboss_text unless emboss_text == SKIP
      @vrn = vrn unless vrn == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      fee_item_id = hash.key?('FeeItemId') ? hash['FeeItemId'] : SKIP
      account_id = hash.key?('AccountId') ? hash['AccountId'] : SKIP
      account_number = hash.key?('AccountNumber') ? hash['AccountNumber'] : SKIP
      account_short_name =
        hash.key?('AccountShortName') ? hash['AccountShortName'] : SKIP
      invoice_account_id =
        hash.key?('InvoiceAccountId') ? hash['InvoiceAccountId'] : SKIP
      invoice_account_number =
        hash.key?('InvoiceAccountNumber') ? hash['InvoiceAccountNumber'] : SKIP
      invoice_account_short_name =
        hash.key?('InvoiceAccountShortName') ? hash['InvoiceAccountShortName'] : SKIP
      payer_id = hash.key?('PayerId') ? hash['PayerId'] : SKIP
      payer_number = hash.key?('PayerNumber') ? hash['PayerNumber'] : SKIP
      payer_short_name =
        hash.key?('PayerShortName') ? hash['PayerShortName'] : SKIP
      card_id = hash.key?('CardId') ? hash['CardId'] : SKIP
      pan = hash.key?('PAN') ? hash['PAN'] : SKIP
      card_group_id = hash.key?('CardGroupId') ? hash['CardGroupId'] : SKIP
      card_group_name =
        hash.key?('CardGroupName') ? hash['CardGroupName'] : SKIP
      fee_type_id = hash.key?('FeeTypeId') ? hash['FeeTypeId'] : SKIP
      fee_type = hash.key?('FeeType') ? hash['FeeType'] : SKIP
      fee_type_group = hash.key?('FeeTypeGroup') ? hash['FeeTypeGroup'] : SKIP
      fee_rule_id = hash.key?('FeeRuleId') ? hash['FeeRuleId'] : SKIP
      fee_rule_description =
        hash.key?('FeeRuleDescription') ? hash['FeeRuleDescription'] : SKIP
      # Parameter is an array, so we need to iterate through it
      fee_rule_tiers = nil
      unless hash['FeeRuleTiers'].nil?
        fee_rule_tiers = []
        hash['FeeRuleTiers'].each do |structure|
          fee_rule_tiers << (FeesFeeRuleTiers.from_hash(structure) if structure)
        end
      end

      fee_rule_tiers = SKIP unless hash.key?('FeeRuleTiers')
      fee_item_date = hash.key?('FeeItemDate') ? hash['FeeItemDate'] : SKIP
      fee_item_time = hash.key?('FeeItemTime') ? hash['FeeItemTime'] : SKIP
      is_manual = hash.key?('IsManual') ? hash['IsManual'] : SKIP
      is_cancelled = hash.key?('IsCancelled') ? hash['IsCancelled'] : SKIP
      customer_currency_code =
        hash.key?('CustomerCurrencyCode') ? hash['CustomerCurrencyCode'] : SKIP
      customer_currency_symbol =
        hash.key?('CustomerCurrencySymbol') ? hash['CustomerCurrencySymbol'] : SKIP
      product_id = hash.key?('ProductId') ? hash['ProductId'] : SKIP
      product_code = hash.key?('ProductCode') ? hash['ProductCode'] : SKIP
      product_name = hash.key?('ProductName') ? hash['ProductName'] : SKIP
      product_group_id =
        hash.key?('ProductGroupId') ? hash['ProductGroupId'] : SKIP
      product_group_name =
        hash.key?('ProductGroupName') ? hash['ProductGroupName'] : SKIP
      line_item_description =
        hash.key?('LineItemDescription') ? hash['LineItemDescription'] : SKIP
      quantity = hash.key?('Quantity') ? hash['Quantity'] : SKIP
      is_invoiced = hash.key?('IsInvoiced') ? hash['IsInvoiced'] : SKIP
      vat_country_code =
        hash.key?('VATCountryCode') ? hash['VATCountryCode'] : SKIP
      vat_country_name =
        hash.key?('VATCountryName') ? hash['VATCountryName'] : SKIP
      vat_percentage = hash.key?('VATPercentage') ? hash['VATPercentage'] : SKIP
      vat_category_id =
        hash.key?('VATCategoryID') ? hash['VATCategoryID'] : SKIP
      vat_category_description =
        hash.key?('VATCategoryDescription') ? hash['VATCategoryDescription'] : SKIP
      legislative_region_id =
        hash.key?('LegislativeRegionId') ? hash['LegislativeRegionId'] : SKIP
      legislative_region_name =
        hash.key?('LegislativeRegionName') ? hash['LegislativeRegionName'] : SKIP
      system_entry_date =
        hash.key?('SystemEntryDate') ? hash['SystemEntryDate'] : SKIP
      system_entry_time =
        hash.key?('SystemEntryTime') ? hash['SystemEntryTime'] : SKIP
      col_co_net_amount =
        hash.key?('ColCoNetAmount') ? hash['ColCoNetAmount'] : SKIP
      col_co_vat_amount =
        hash.key?('ColCoVATAmount') ? hash['ColCoVATAmount'] : SKIP
      col_co_gross_amount =
        hash.key?('ColCoGrossAmount') ? hash['ColCoGrossAmount'] : SKIP
      interim_invoice_id =
        hash.key?('InterimInvoiceId') ? hash['InterimInvoiceId'] : SKIP
      interim_invoice_number =
        hash.key?('InterimInvoiceNumber') ? hash['InterimInvoiceNumber'] : SKIP
      invoice_id = hash.key?('InvoiceId') ? hash['InvoiceId'] : SKIP
      invoice_number = hash.key?('InvoiceNumber') ? hash['InvoiceNumber'] : SKIP
      invoice_date = hash.key?('InvoiceDate') ? hash['InvoiceDate'] : SKIP
      customer_exchange_rate =
        hash.key?('CustomerExchangeRate') ? hash['CustomerExchangeRate'] : SKIP
      invoice_net_amount =
        hash.key?('InvoiceNetAmount') ? hash['InvoiceNetAmount'] : SKIP
      invoice_gross_amount =
        hash.key?('InvoiceGrossAmount') ? hash['InvoiceGrossAmount'] : SKIP
      invoice_vat_amount =
        hash.key?('InvoiceVATAmount') ? hash['InvoiceVATAmount'] : SKIP
      reverse_charge = hash.key?('ReverseCharge') ? hash['ReverseCharge'] : SKIP
      original_fee_item_id =
        hash.key?('OriginalFeeItemId') ? hash['OriginalFeeItemId'] : SKIP
      original_currency_code =
        hash.key?('OriginalCurrencyCode') ? hash['OriginalCurrencyCode'] : SKIP
      original_currency_symbol =
        hash.key?('OriginalCurrencySymbol') ? hash['OriginalCurrencySymbol'] : SKIP
      original_unit_price =
        hash.key?('OriginalUnitPrice') ? hash['OriginalUnitPrice'] : SKIP
      original_net_amount =
        hash.key?('OriginalNetAmount') ? hash['OriginalNetAmount'] : SKIP
      original_vat_amount =
        hash.key?('OriginalVATAmount') ? hash['OriginalVATAmount'] : SKIP
      original_gross_amount =
        hash.key?('OriginalGrossAmount') ? hash['OriginalGrossAmount'] : SKIP
      original_exchange_rate =
        hash.key?('OriginalExchangeRate') ? hash['OriginalExchangeRate'] : SKIP
      original_legislative_region_id =
        hash.key?('OriginalLegislativeRegionId') ? hash['OriginalLegislativeRegionId'] : SKIP
      original_legislative_region_name =
        hash.key?('OriginalLegislativeRegionName') ? hash['OriginalLegislativeRegionName'] : SKIP
      frequency = hash.key?('Frequency') ? hash['Frequency'] : SKIP
      fee_item_card_level_breakup =
        hash.key?('FeeItemCardLevelBreakup') ? hash['FeeItemCardLevelBreakup'] : SKIP
      original_fee_item_invoice_id =
        hash.key?('OriginalFeeItemInvoiceId') ? hash['OriginalFeeItemInvoiceId'] : SKIP
      original_fee_item_invoice_number =
        hash.key?('OriginalFeeItemInvoiceNumber') ? hash['OriginalFeeItemInvoiceNumber'] : SKIP
      original_fee_item_invoice_date =
        hash.key?('OriginalFeeItemInvoiceDate') ? hash['OriginalFeeItemInvoiceDate'] : SKIP
      driver_name = hash.key?('DriverName') ? hash['DriverName'] : SKIP
      emboss_text = hash.key?('EmbossText') ? hash['EmbossText'] : SKIP
      vrn = hash.key?('VRN') ? hash['VRN'] : SKIP

      # Create object from extracted values.
      FeeItem.new(fee_item_id,
                  account_id,
                  account_number,
                  account_short_name,
                  invoice_account_id,
                  invoice_account_number,
                  invoice_account_short_name,
                  payer_id,
                  payer_number,
                  payer_short_name,
                  card_id,
                  pan,
                  card_group_id,
                  card_group_name,
                  fee_type_id,
                  fee_type,
                  fee_type_group,
                  fee_rule_id,
                  fee_rule_description,
                  fee_rule_tiers,
                  fee_item_date,
                  fee_item_time,
                  is_manual,
                  is_cancelled,
                  customer_currency_code,
                  customer_currency_symbol,
                  product_id,
                  product_code,
                  product_name,
                  product_group_id,
                  product_group_name,
                  line_item_description,
                  quantity,
                  is_invoiced,
                  vat_country_code,
                  vat_country_name,
                  vat_percentage,
                  vat_category_id,
                  vat_category_description,
                  legislative_region_id,
                  legislative_region_name,
                  system_entry_date,
                  system_entry_time,
                  col_co_net_amount,
                  col_co_vat_amount,
                  col_co_gross_amount,
                  interim_invoice_id,
                  interim_invoice_number,
                  invoice_id,
                  invoice_number,
                  invoice_date,
                  customer_exchange_rate,
                  invoice_net_amount,
                  invoice_gross_amount,
                  invoice_vat_amount,
                  reverse_charge,
                  original_fee_item_id,
                  original_currency_code,
                  original_currency_symbol,
                  original_unit_price,
                  original_net_amount,
                  original_vat_amount,
                  original_gross_amount,
                  original_exchange_rate,
                  original_legislative_region_id,
                  original_legislative_region_name,
                  frequency,
                  fee_item_card_level_breakup,
                  original_fee_item_invoice_id,
                  original_fee_item_invoice_number,
                  original_fee_item_invoice_date,
                  driver_name,
                  emboss_text,
                  vrn)
    end
  end
end
