# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # Invoice document reference number for the additional invoice files such as
  # KSeF file (Poland). This field is optional, and it will be missing if
  # additional documents are not applicable. Also, it will not be populated if
  # the invoice date is older than 13 months.
  class InvoiceSearchAdditionalDocument < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Unique ID for the additional invoice document.
    # @return [String]
    attr_accessor :reference

    # Type of the additional document.
    # Mandatory
    # Possible values:
    # •	KSeF - Applicable for Poland market.
    # @return [String]
    attr_accessor :type

    # True if a KSeF PDF will be produced for the customer.
    # @return [String]
    attr_accessor :is_applicable

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['reference'] = 'Reference'
      @_hash['type'] = 'Type'
      @_hash['is_applicable'] = 'IsApplicable'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        reference
        type
        is_applicable
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        reference
        type
        is_applicable
      ]
    end

    def initialize(reference = SKIP,
                   type = SKIP,
                   is_applicable = SKIP)
      @reference = reference unless reference == SKIP
      @type = type unless type == SKIP
      @is_applicable = is_applicable unless is_applicable == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      reference = hash.key?('Reference') ? hash['Reference'] : SKIP
      type = hash.key?('Type') ? hash['Type'] : SKIP
      is_applicable = hash.key?('IsApplicable') ? hash['IsApplicable'] : SKIP

      # Create object from extracted values.
      InvoiceSearchAdditionalDocument.new(reference,
                                          type,
                                          is_applicable)
    end
  end
end
