# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # InvoiceSummaryDetails Model.
  class InvoiceSummaryDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Total number of invoices matching with the given search criteria.
    # @return [Integer]
    attr_accessor :total_invoices

    # Total gross amount in customer currency combined from all the invoices
    # matching with the given search criteria.
    # @return [Float]
    attr_accessor :total_gross_amount_customer_currency

    # Total net amount in customer currency combined from all the invoices
    # matching with the given search criteria.
    # @return [Float]
    attr_accessor :total_net_amount_customer_currency

    # Total VAT amount in customer currency combined from all the invoices
    # matching with the given search criteria.
    # @return [Float]
    attr_accessor :total_vat_amount_customer_currency

    # Customer currency ISO code.
    # Example: EUR
    # @return [String]
    attr_accessor :customer_currency_code

    # Customer currency code.
    # Example: €
    # @return [String]
    attr_accessor :customer_currency_symbol

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['total_invoices'] = 'TotalInvoices'
      @_hash['total_gross_amount_customer_currency'] =
        'TotalGrossAmountCustomerCurrency'
      @_hash['total_net_amount_customer_currency'] =
        'TotalNetAmountCustomerCurrency'
      @_hash['total_vat_amount_customer_currency'] =
        'TotalVATAmountCustomerCurrency'
      @_hash['customer_currency_code'] = 'CustomerCurrencyCode'
      @_hash['customer_currency_symbol'] = 'CustomerCurrencySymbol'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        total_invoices
        total_gross_amount_customer_currency
        total_net_amount_customer_currency
        total_vat_amount_customer_currency
        customer_currency_code
        customer_currency_symbol
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        total_invoices
        total_gross_amount_customer_currency
        total_net_amount_customer_currency
        total_vat_amount_customer_currency
        customer_currency_code
        customer_currency_symbol
      ]
    end

    def initialize(total_invoices = SKIP,
                   total_gross_amount_customer_currency = SKIP,
                   total_net_amount_customer_currency = SKIP,
                   total_vat_amount_customer_currency = SKIP,
                   customer_currency_code = SKIP,
                   customer_currency_symbol = SKIP)
      @total_invoices = total_invoices unless total_invoices == SKIP
      unless total_gross_amount_customer_currency == SKIP
        @total_gross_amount_customer_currency =
          total_gross_amount_customer_currency
      end
      unless total_net_amount_customer_currency == SKIP
        @total_net_amount_customer_currency =
          total_net_amount_customer_currency
      end
      unless total_vat_amount_customer_currency == SKIP
        @total_vat_amount_customer_currency =
          total_vat_amount_customer_currency
      end
      @customer_currency_code = customer_currency_code unless customer_currency_code == SKIP
      @customer_currency_symbol = customer_currency_symbol unless customer_currency_symbol == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      total_invoices = hash.key?('TotalInvoices') ? hash['TotalInvoices'] : SKIP
      total_gross_amount_customer_currency =
        hash.key?('TotalGrossAmountCustomerCurrency') ? hash['TotalGrossAmountCustomerCurrency'] : SKIP
      total_net_amount_customer_currency =
        hash.key?('TotalNetAmountCustomerCurrency') ? hash['TotalNetAmountCustomerCurrency'] : SKIP
      total_vat_amount_customer_currency =
        hash.key?('TotalVATAmountCustomerCurrency') ? hash['TotalVATAmountCustomerCurrency'] : SKIP
      customer_currency_code =
        hash.key?('CustomerCurrencyCode') ? hash['CustomerCurrencyCode'] : SKIP
      customer_currency_symbol =
        hash.key?('CustomerCurrencySymbol') ? hash['CustomerCurrencySymbol'] : SKIP

      # Create object from extracted values.
      InvoiceSummaryDetails.new(total_invoices,
                                total_gross_amount_customer_currency,
                                total_net_amount_customer_currency,
                                total_vat_amount_customer_currency,
                                customer_currency_code,
                                customer_currency_symbol)
    end
  end
end
