# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # InvoicesSummaries Model.
  class InvoicesSummaries < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Amount due from last summary document date.
    # @return [Float]
    attr_accessor :amount_due

    # Amount that are due from past summary documents.
    # @return [Float]
    attr_accessor :amount_not_overdue

    # Amount that are overdue from past summary documents.
    # @return [Float]
    attr_accessor :amount_overdue

    # Total amount paid in billing currency.
    # @return [Float]
    attr_accessor :amount_paid

    # Billing currency ISO code.
    # @return [String]
    attr_accessor :billing_currency_code

    # Billing currency symbol.
    # Example: €
    # @return [String]
    attr_accessor :billing_currency_symbol

    # Current outstanding balance amount
    # @return [Float]
    attr_accessor :outstanding_balance

    # Payment due date.
    # Format: YYYYMMDD
    # @return [String]
    attr_accessor :payment_due_date

    # Summary document date.
    # Format: YYYYMMDD
    # @return [String]
    attr_accessor :summary_document_date

    # Total number of invoices generated on this date.
    # @return [Integer]
    attr_accessor :total_billing_documents

    # Total gross amount in billing currency.
    # @return [Float]
    attr_accessor :total_gross_amount_billing_currency

    # Total net amount in billing currency.
    # @return [Float]
    attr_accessor :total_net_amount_billing_currency

    # Total number of summary documents generated on this date.
    # @return [Integer]
    attr_accessor :total_summary_documents

    # Total VAT amount in billing currency.
    # @return [Float]
    attr_accessor :total_vat_amount_billing_currency

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['amount_due'] = 'AmountDue'
      @_hash['amount_not_overdue'] = 'AmountNotOverdue'
      @_hash['amount_overdue'] = 'AmountOverdue'
      @_hash['amount_paid'] = 'AmountPaid'
      @_hash['billing_currency_code'] = 'BillingCurrencyCode'
      @_hash['billing_currency_symbol'] = 'BillingCurrencySymbol'
      @_hash['outstanding_balance'] = 'OutstandingBalance'
      @_hash['payment_due_date'] = 'PaymentDueDate'
      @_hash['summary_document_date'] = 'SummaryDocumentDate'
      @_hash['total_billing_documents'] = 'TotalBillingDocuments'
      @_hash['total_gross_amount_billing_currency'] =
        'TotalGrossAmountBillingCurrency'
      @_hash['total_net_amount_billing_currency'] =
        'TotalNetAmountBillingCurrency'
      @_hash['total_summary_documents'] = 'TotalSummaryDocuments'
      @_hash['total_vat_amount_billing_currency'] =
        'TotalVATAmountBillingCurrency'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        amount_due
        amount_not_overdue
        amount_overdue
        amount_paid
        billing_currency_code
        billing_currency_symbol
        outstanding_balance
        payment_due_date
        summary_document_date
        total_billing_documents
        total_gross_amount_billing_currency
        total_net_amount_billing_currency
        total_summary_documents
        total_vat_amount_billing_currency
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        amount_due
        amount_not_overdue
        amount_overdue
        amount_paid
        billing_currency_code
        billing_currency_symbol
        outstanding_balance
        payment_due_date
        summary_document_date
        total_billing_documents
        total_gross_amount_billing_currency
        total_net_amount_billing_currency
        total_summary_documents
        total_vat_amount_billing_currency
      ]
    end

    def initialize(amount_due = SKIP,
                   amount_not_overdue = SKIP,
                   amount_overdue = SKIP,
                   amount_paid = SKIP,
                   billing_currency_code = SKIP,
                   billing_currency_symbol = SKIP,
                   outstanding_balance = SKIP,
                   payment_due_date = SKIP,
                   summary_document_date = SKIP,
                   total_billing_documents = SKIP,
                   total_gross_amount_billing_currency = SKIP,
                   total_net_amount_billing_currency = SKIP,
                   total_summary_documents = SKIP,
                   total_vat_amount_billing_currency = SKIP)
      @amount_due = amount_due unless amount_due == SKIP
      @amount_not_overdue = amount_not_overdue unless amount_not_overdue == SKIP
      @amount_overdue = amount_overdue unless amount_overdue == SKIP
      @amount_paid = amount_paid unless amount_paid == SKIP
      @billing_currency_code = billing_currency_code unless billing_currency_code == SKIP
      @billing_currency_symbol = billing_currency_symbol unless billing_currency_symbol == SKIP
      @outstanding_balance = outstanding_balance unless outstanding_balance == SKIP
      @payment_due_date = payment_due_date unless payment_due_date == SKIP
      @summary_document_date = summary_document_date unless summary_document_date == SKIP
      @total_billing_documents = total_billing_documents unless total_billing_documents == SKIP
      unless total_gross_amount_billing_currency == SKIP
        @total_gross_amount_billing_currency =
          total_gross_amount_billing_currency
      end
      unless total_net_amount_billing_currency == SKIP
        @total_net_amount_billing_currency =
          total_net_amount_billing_currency
      end
      @total_summary_documents = total_summary_documents unless total_summary_documents == SKIP
      unless total_vat_amount_billing_currency == SKIP
        @total_vat_amount_billing_currency =
          total_vat_amount_billing_currency
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      amount_due = hash.key?('AmountDue') ? hash['AmountDue'] : SKIP
      amount_not_overdue =
        hash.key?('AmountNotOverdue') ? hash['AmountNotOverdue'] : SKIP
      amount_overdue = hash.key?('AmountOverdue') ? hash['AmountOverdue'] : SKIP
      amount_paid = hash.key?('AmountPaid') ? hash['AmountPaid'] : SKIP
      billing_currency_code =
        hash.key?('BillingCurrencyCode') ? hash['BillingCurrencyCode'] : SKIP
      billing_currency_symbol =
        hash.key?('BillingCurrencySymbol') ? hash['BillingCurrencySymbol'] : SKIP
      outstanding_balance =
        hash.key?('OutstandingBalance') ? hash['OutstandingBalance'] : SKIP
      payment_due_date =
        hash.key?('PaymentDueDate') ? hash['PaymentDueDate'] : SKIP
      summary_document_date =
        hash.key?('SummaryDocumentDate') ? hash['SummaryDocumentDate'] : SKIP
      total_billing_documents =
        hash.key?('TotalBillingDocuments') ? hash['TotalBillingDocuments'] : SKIP
      total_gross_amount_billing_currency =
        hash.key?('TotalGrossAmountBillingCurrency') ? hash['TotalGrossAmountBillingCurrency'] : SKIP
      total_net_amount_billing_currency =
        hash.key?('TotalNetAmountBillingCurrency') ? hash['TotalNetAmountBillingCurrency'] : SKIP
      total_summary_documents =
        hash.key?('TotalSummaryDocuments') ? hash['TotalSummaryDocuments'] : SKIP
      total_vat_amount_billing_currency =
        hash.key?('TotalVATAmountBillingCurrency') ? hash['TotalVATAmountBillingCurrency'] : SKIP

      # Create object from extracted values.
      InvoicesSummaries.new(amount_due,
                            amount_not_overdue,
                            amount_overdue,
                            amount_paid,
                            billing_currency_code,
                            billing_currency_symbol,
                            outstanding_balance,
                            payment_due_date,
                            summary_document_date,
                            total_billing_documents,
                            total_gross_amount_billing_currency,
                            total_net_amount_billing_currency,
                            total_summary_documents,
                            total_vat_amount_billing_currency)
    end
  end
end
