# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # InvoiceSearchDetails Model.
  class InvoiceSearchDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Account Full Name
    # Example: AT_reversal customer_FN
    # @return [String]
    attr_accessor :account_full_name

    # Account ID
    # Example: 29484
    # @return [Integer]
    attr_accessor :account_id

    # Account Number
    # Example: GB99215176
    # @return [String]
    attr_accessor :account_number

    # Account Short Name
    # Example: AT Earth Movers-SN
    # @return [String]
    attr_accessor :account_short_name

    # ColCo Id.
    # Example: 18
    # @return [Integer]
    attr_accessor :col_co_id

    # ColCo’s OpCo Id.
    # Example: 018
    # @return [String]
    attr_accessor :col_co_op_co_id

    # Current billing frequency of the account.
    # A few of the possible IDs and Description are below:
    # 1    Daily (all days)
    # 2    Daily (only working days)
    # 3    Weekly - Monday
    # 4    Weekly - Tuesday
    # 5    Weekly - Wednesday
    # 6    Weekly - Thursday
    # 7    Weekly - Friday
    # 8    Weekly - Saturday
    # 9    Weekly - Sunday
    # 10    Monthly - 1st
    # Example: Weekly – Wednesday
    # @return [String]
    attr_accessor :current_billing_frequency

    # Current billing frequency id of the account.
    # A few of the possible IDs and Description are below:
    # 1    Daily (all days)
    # 2    Daily (only working days)
    # 3    Weekly - Monday
    # 4    Weekly - Tuesday
    # 5    Weekly - Wednesday
    # 6    Weekly - Thursday
    # 7    Weekly - Friday
    # 8    Weekly - Saturday
    # 9    Weekly - Sunday
    # 10    Monthly - 1st
    # Example: 5
    # @return [Integer]
    attr_accessor :current_billing_frequency_id

    # Current distribution method name of the account.
    # Example : Id & Description
    # 1    e-mail
    # 2    Fax
    # 3    Courier to Customer
    # 4    Courier to Client
    # 5    Print
    # 6    FTP
    # 7    SMS
    # @return [String]
    attr_accessor :current_distribution_method

    # Current distribution method id of the account.
    # Example : Id & Description
    # 1    e-mail
    # 2    Fax
    # 3    Courier to Customer
    # 4    Courier to Client
    # 5    Print
    # 6    FTP
    # 7    SMS
    # @return [Integer]
    attr_accessor :current_distribution_method_id

    # Customer currency ISO code.
    # Example: EUR
    # @return [String]
    attr_accessor :customer_currency_code

    # Customer currency code.
    # Example: €
    # @return [String]
    attr_accessor :customer_currency_symbol

    # DelCo’s client company number.
    # Example: 132
    # @return [String]
    attr_accessor :del_co_client_number

    # DelCo Id.
    # Example: 132
    # @return [Integer]
    attr_accessor :del_co_id

    # DelCo’s OpCo Id.
    # Example: 032
    # @return [String]
    attr_accessor :del_co_op_co_id

    # Document type Id description.
    # @return [String]
    attr_accessor :document_type

    # Document type Id.
    # @return [Integer]
    attr_accessor :document_type_id

    # Due date. Format: yyyyMMdd.
    # Example: 20170115
    # @return [String]
    attr_accessor :due_date

    # Gross amount in customer currency in the document.
    # @return [Float]
    attr_accessor :gross_amount_customer_currency

    # Gross amount in transaction currency in the document
    # @return [Float]
    attr_accessor :gross_amount_transaction_currency

    # Invoicing date. Format: yyyyMMdd
    # Example: 20170101
    # @return [String]
    attr_accessor :invoice_date

    # Company name.
    # @return [String]
    attr_accessor :invoiced_by

    # Country Name.
    # Example: Czech Republic
    # @return [String]
    attr_accessor :invoiced_on_behalf_of

    # Invoice id.
    # Example: 1
    # @return [Integer]
    attr_accessor :invoice_id

    # Invoice number.
    # Example: 0123456789
    # @return [String]
    attr_accessor :invoice_number

    # True/False.
    # True if this is an International invoice, else false.
    # @return [TrueClass | FalseClass]
    attr_accessor :is_international

    # True/False.
    # True if this is a National invoice, else false.
    # @return [TrueClass | FalseClass]
    attr_accessor :is_national

    # Net amount in customer currency in the document.
    # @return [Float]
    attr_accessor :net_amount_customer_currency

    # Net amount in transaction currency in the document.
    # @return [Float]
    attr_accessor :net_amount_transaction_currency

    # Payment customer id of the customer.
    # Example: 123456
    # @return [Integer]
    attr_accessor :payer_id

    # Payment customer number.
    # Example: GB000000123
    # @return [String]
    attr_accessor :payer_number

    # A few of the possible IDs and Descriptions are below:
    # 1    14 days after Invoice
    # 2    15 days after Invoice
    # 3    21 days after Invoice
    # 4    30 days after Invoice
    # 5    45 days after Invoice
    # @return [String]
    attr_accessor :payment_terms

    # Payment terms id of the payment customer.
    # A few of the possible IDs and Descriptions are below:
    # 1    14 days after Invoice
    # 2    15 days after Invoice
    # 3    21 days after Invoice
    # 4    30 days after Invoice
    # 5    45 days after Invoice
    # @return [Integer]
    attr_accessor :payment_terms_id

    # Replaced document id.
    # Example: 2
    # @return [Integer]
    attr_accessor :replacement_invoice_id

    # Reversed document id. 
    # Example: 3
    # @return [Integer]
    attr_accessor :reversal_invoice_id

    # Status of the document. Valid values –
    # •    [Empty] – For all document types except for Invoice and Statement.
    # •    Due – Invoices/Statements due for payment and is within the due date.
    # •    Paid – Fully paid Invoices/Statements.
    # Overdue – Invoices/Statements due of payment and has crossed the due date.
    # @return [String]
    attr_accessor :status

    # Billing type description.
    # Example: Id & Description
    # -3    Guarantee History
    # -1    Initial Balance
    # 0    Standard Invoice
    # 1    Immediate Invoice
    # 2    Guarantee
    # 4    Advanced DD Invoice
    # @return [String]
    attr_accessor :summary_document_billing_type

    # Billing type id.
    # Example: Id & Description
    # -3    Guarantee History
    # -1    Initial Balance
    # 0    Standard Invoice
    # 1    Immediate Invoice
    # 2    Guarantee
    # 4    Advanced DD Invoice
    # @return [Integer]
    attr_accessor :summary_document_billing_type_id

    # Document generated date. Format: yyyyMMdd
    # Example: 20170101
    # @return [String]
    attr_accessor :summary_document_date

    # DD amount.
    # @return [Float]
    attr_accessor :summary_document_dd_amount

    # Due date for document. Format: yyyyMMdd
    # Example: 20170115
    # @return [String]
    attr_accessor :summary_document_due_date

    # Summary document identifier
    # Example: 1
    # @return [Integer]
    attr_accessor :summary_document_id

    # True/False
    # True if invoice amount is fully paid, else false
    # @return [TrueClass | FalseClass]
    attr_accessor :summary_document_is_fully_paid

    # Summary document number
    # Example: ‘0/CZ0000000123456/2017’
    # @return [String]
    attr_accessor :summary_document_number

    # Total amount paid.
    # @return [Float]
    attr_accessor :summary_document_paid_amount

    # Statement of Account reference number of the payment customer.
    # @return [String]
    attr_accessor :summary_document_so_a_reference_number

    # Statement of Account Id of the payment customer.
    # @return [Integer]
    attr_accessor :summary_document_statement_of_account_id

    # Transaction currency ISO code.
    # Example: EUR
    # @return [String]
    attr_accessor :transaction_currency_code

    # Transaction currency symbol.
    # Example: €
    # @return [String]
    attr_accessor :transaction_currency_symbol

    # Invoice type description.
    # A few of the possible IDs and Description are below:
    # 1    Original
    # 2    Reversal
    # 3    Replacement
    # Example: Original
    # @return [String]
    attr_accessor :type

    # Invoice type id.
    # A few of the possible IDs and Descriptions are below:
    # 1    Original
    # 2    Reversal
    # 3    Replacement
    # Example: 1
    # @return [Integer]
    attr_accessor :type_id

    # VAT amount in customer currency in the document
    # @return [Float]
    attr_accessor :vat_amount_customer_currency

    # VAT amount in transaction currency in the document
    # @return [Float]
    attr_accessor :vat_amount_transaction_currency

    # Country name of the VAT country.
    # Example: France, Germany
    # @return [String]
    attr_accessor :vat_country

    # Country Id of the VAT country.
    # Example: 1,2
    # @return [Integer]
    attr_accessor :vat_country_id

    # Country ISO code of the VAT country.
    # Example : CZ, SK, UK, etc.,
    # @return [String]
    attr_accessor :vat_country_iso_code

    # VAT country’s OpCo Id.
    # Example: 032
    # @return [String]
    attr_accessor :vat_country_op_co_id

    # document reference number of the Invoice file
    # @return [String]
    attr_accessor :document_reference

    # document reference number of the Invoice file
    # @return [Array[InvoiceSearchAdditionalDocument]]
    attr_accessor :additional_documents

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_full_name'] = 'AccountFullName'
      @_hash['account_id'] = 'AccountId'
      @_hash['account_number'] = 'AccountNumber'
      @_hash['account_short_name'] = 'AccountShortName'
      @_hash['col_co_id'] = 'ColCoId'
      @_hash['col_co_op_co_id'] = 'ColCoOpCoId'
      @_hash['current_billing_frequency'] = 'CurrentBillingFrequency'
      @_hash['current_billing_frequency_id'] = 'CurrentBillingFrequencyId'
      @_hash['current_distribution_method'] = 'CurrentDistributionMethod'
      @_hash['current_distribution_method_id'] = 'CurrentDistributionMethodId'
      @_hash['customer_currency_code'] = 'CustomerCurrencyCode'
      @_hash['customer_currency_symbol'] = 'CustomerCurrencySymbol'
      @_hash['del_co_client_number'] = 'DelCoClientNumber'
      @_hash['del_co_id'] = 'DelCoId'
      @_hash['del_co_op_co_id'] = 'DelCoOpCoId'
      @_hash['document_type'] = 'DocumentType'
      @_hash['document_type_id'] = 'DocumentTypeId'
      @_hash['due_date'] = 'DueDate'
      @_hash['gross_amount_customer_currency'] = 'GrossAmountCustomerCurrency'
      @_hash['gross_amount_transaction_currency'] =
        'GrossAmountTransactionCurrency'
      @_hash['invoice_date'] = 'InvoiceDate'
      @_hash['invoiced_by'] = 'InvoicedBy'
      @_hash['invoiced_on_behalf_of'] = 'InvoicedOnBehalfOf'
      @_hash['invoice_id'] = 'InvoiceId'
      @_hash['invoice_number'] = 'InvoiceNumber'
      @_hash['is_international'] = 'IsInternational'
      @_hash['is_national'] = 'IsNational'
      @_hash['net_amount_customer_currency'] = 'NetAmountCustomerCurrency'
      @_hash['net_amount_transaction_currency'] =
        'NetAmountTransactionCurrency'
      @_hash['payer_id'] = 'PayerId'
      @_hash['payer_number'] = 'PayerNumber'
      @_hash['payment_terms'] = 'PaymentTerms'
      @_hash['payment_terms_id'] = 'PaymentTermsId'
      @_hash['replacement_invoice_id'] = 'ReplacementInvoiceId'
      @_hash['reversal_invoice_id'] = 'ReversalInvoiceId'
      @_hash['status'] = 'Status'
      @_hash['summary_document_billing_type'] = 'SummaryDocumentBillingType'
      @_hash['summary_document_billing_type_id'] =
        'SummaryDocumentBillingTypeId'
      @_hash['summary_document_date'] = 'SummaryDocumentDate'
      @_hash['summary_document_dd_amount'] = 'SummaryDocumentDDAmount'
      @_hash['summary_document_due_date'] = 'SummaryDocumentDueDate'
      @_hash['summary_document_id'] = 'SummaryDocumentId'
      @_hash['summary_document_is_fully_paid'] = 'SummaryDocumentIsFullyPaid'
      @_hash['summary_document_number'] = 'SummaryDocumentNumber'
      @_hash['summary_document_paid_amount'] = 'SummaryDocumentPaidAmount'
      @_hash['summary_document_so_a_reference_number'] =
        'SummaryDocumentSoAReferenceNumber'
      @_hash['summary_document_statement_of_account_id'] =
        'SummaryDocumentStatementOfAccountId'
      @_hash['transaction_currency_code'] = 'TransactionCurrencyCode'
      @_hash['transaction_currency_symbol'] = 'TransactionCurrencySymbol'
      @_hash['type'] = 'Type'
      @_hash['type_id'] = 'TypeId'
      @_hash['vat_amount_customer_currency'] = 'VATAmountCustomerCurrency'
      @_hash['vat_amount_transaction_currency'] =
        'VATAmountTransactionCurrency'
      @_hash['vat_country'] = 'VATCountry'
      @_hash['vat_country_id'] = 'VATCountryId'
      @_hash['vat_country_iso_code'] = 'VATCountryISOCode'
      @_hash['vat_country_op_co_id'] = 'VATCountryOpCoId'
      @_hash['document_reference'] = 'DocumentReference'
      @_hash['additional_documents'] = 'AdditionalDocuments'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_full_name
        account_id
        account_number
        account_short_name
        col_co_id
        col_co_op_co_id
        current_billing_frequency
        current_billing_frequency_id
        current_distribution_method
        current_distribution_method_id
        customer_currency_code
        customer_currency_symbol
        del_co_client_number
        del_co_id
        del_co_op_co_id
        document_type
        document_type_id
        due_date
        gross_amount_customer_currency
        gross_amount_transaction_currency
        invoice_date
        invoiced_by
        invoiced_on_behalf_of
        invoice_id
        invoice_number
        is_international
        is_national
        net_amount_customer_currency
        net_amount_transaction_currency
        payer_id
        payer_number
        payment_terms
        payment_terms_id
        replacement_invoice_id
        reversal_invoice_id
        status
        summary_document_billing_type
        summary_document_billing_type_id
        summary_document_date
        summary_document_dd_amount
        summary_document_due_date
        summary_document_id
        summary_document_is_fully_paid
        summary_document_number
        summary_document_paid_amount
        summary_document_so_a_reference_number
        summary_document_statement_of_account_id
        transaction_currency_code
        transaction_currency_symbol
        type
        type_id
        vat_amount_customer_currency
        vat_amount_transaction_currency
        vat_country
        vat_country_id
        vat_country_iso_code
        vat_country_op_co_id
        document_reference
        additional_documents
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_full_name
        account_id
        account_number
        account_short_name
        col_co_id
        col_co_op_co_id
        current_billing_frequency
        current_billing_frequency_id
        current_distribution_method
        current_distribution_method_id
        customer_currency_code
        customer_currency_symbol
        del_co_client_number
        del_co_id
        del_co_op_co_id
        document_type
        document_type_id
        due_date
        gross_amount_customer_currency
        gross_amount_transaction_currency
        invoice_date
        invoiced_by
        invoiced_on_behalf_of
        invoice_id
        invoice_number
        is_international
        is_national
        net_amount_customer_currency
        net_amount_transaction_currency
        payer_id
        payer_number
        payment_terms
        payment_terms_id
        replacement_invoice_id
        reversal_invoice_id
        status
        summary_document_billing_type
        summary_document_billing_type_id
        summary_document_date
        summary_document_dd_amount
        summary_document_due_date
        summary_document_id
        summary_document_is_fully_paid
        summary_document_number
        summary_document_paid_amount
        summary_document_so_a_reference_number
        summary_document_statement_of_account_id
        transaction_currency_code
        transaction_currency_symbol
        type
        type_id
        vat_amount_customer_currency
        vat_amount_transaction_currency
        vat_country
        vat_country_id
        vat_country_iso_code
        vat_country_op_co_id
        document_reference
      ]
    end

    def initialize(account_full_name = SKIP, account_id = SKIP,
                   account_number = SKIP, account_short_name = SKIP,
                   col_co_id = SKIP, col_co_op_co_id = SKIP,
                   current_billing_frequency = SKIP,
                   current_billing_frequency_id = SKIP,
                   current_distribution_method = SKIP,
                   current_distribution_method_id = SKIP,
                   customer_currency_code = SKIP,
                   customer_currency_symbol = SKIP, del_co_client_number = SKIP,
                   del_co_id = SKIP, del_co_op_co_id = SKIP,
                   document_type = SKIP, document_type_id = SKIP,
                   due_date = SKIP, gross_amount_customer_currency = SKIP,
                   gross_amount_transaction_currency = SKIP,
                   invoice_date = SKIP, invoiced_by = SKIP,
                   invoiced_on_behalf_of = SKIP, invoice_id = SKIP,
                   invoice_number = SKIP, is_international = SKIP,
                   is_national = SKIP, net_amount_customer_currency = SKIP,
                   net_amount_transaction_currency = SKIP, payer_id = SKIP,
                   payer_number = SKIP, payment_terms = SKIP,
                   payment_terms_id = SKIP, replacement_invoice_id = SKIP,
                   reversal_invoice_id = SKIP, status = SKIP,
                   summary_document_billing_type = SKIP,
                   summary_document_billing_type_id = SKIP,
                   summary_document_date = SKIP,
                   summary_document_dd_amount = SKIP,
                   summary_document_due_date = SKIP, summary_document_id = SKIP,
                   summary_document_is_fully_paid = SKIP,
                   summary_document_number = SKIP,
                   summary_document_paid_amount = SKIP,
                   summary_document_so_a_reference_number = SKIP,
                   summary_document_statement_of_account_id = SKIP,
                   transaction_currency_code = SKIP,
                   transaction_currency_symbol = SKIP, type = SKIP,
                   type_id = SKIP, vat_amount_customer_currency = SKIP,
                   vat_amount_transaction_currency = SKIP, vat_country = SKIP,
                   vat_country_id = SKIP, vat_country_iso_code = SKIP,
                   vat_country_op_co_id = SKIP, document_reference = SKIP,
                   additional_documents = SKIP)
      @account_full_name = account_full_name unless account_full_name == SKIP
      @account_id = account_id unless account_id == SKIP
      @account_number = account_number unless account_number == SKIP
      @account_short_name = account_short_name unless account_short_name == SKIP
      @col_co_id = col_co_id unless col_co_id == SKIP
      @col_co_op_co_id = col_co_op_co_id unless col_co_op_co_id == SKIP
      unless current_billing_frequency == SKIP
        @current_billing_frequency =
          current_billing_frequency
      end
      unless current_billing_frequency_id == SKIP
        @current_billing_frequency_id =
          current_billing_frequency_id
      end
      unless current_distribution_method == SKIP
        @current_distribution_method =
          current_distribution_method
      end
      unless current_distribution_method_id == SKIP
        @current_distribution_method_id =
          current_distribution_method_id
      end
      @customer_currency_code = customer_currency_code unless customer_currency_code == SKIP
      @customer_currency_symbol = customer_currency_symbol unless customer_currency_symbol == SKIP
      @del_co_client_number = del_co_client_number unless del_co_client_number == SKIP
      @del_co_id = del_co_id unless del_co_id == SKIP
      @del_co_op_co_id = del_co_op_co_id unless del_co_op_co_id == SKIP
      @document_type = document_type unless document_type == SKIP
      @document_type_id = document_type_id unless document_type_id == SKIP
      @due_date = due_date unless due_date == SKIP
      unless gross_amount_customer_currency == SKIP
        @gross_amount_customer_currency =
          gross_amount_customer_currency
      end
      unless gross_amount_transaction_currency == SKIP
        @gross_amount_transaction_currency =
          gross_amount_transaction_currency
      end
      @invoice_date = invoice_date unless invoice_date == SKIP
      @invoiced_by = invoiced_by unless invoiced_by == SKIP
      @invoiced_on_behalf_of = invoiced_on_behalf_of unless invoiced_on_behalf_of == SKIP
      @invoice_id = invoice_id unless invoice_id == SKIP
      @invoice_number = invoice_number unless invoice_number == SKIP
      @is_international = is_international unless is_international == SKIP
      @is_national = is_national unless is_national == SKIP
      unless net_amount_customer_currency == SKIP
        @net_amount_customer_currency =
          net_amount_customer_currency
      end
      unless net_amount_transaction_currency == SKIP
        @net_amount_transaction_currency =
          net_amount_transaction_currency
      end
      @payer_id = payer_id unless payer_id == SKIP
      @payer_number = payer_number unless payer_number == SKIP
      @payment_terms = payment_terms unless payment_terms == SKIP
      @payment_terms_id = payment_terms_id unless payment_terms_id == SKIP
      @replacement_invoice_id = replacement_invoice_id unless replacement_invoice_id == SKIP
      @reversal_invoice_id = reversal_invoice_id unless reversal_invoice_id == SKIP
      @status = status unless status == SKIP
      unless summary_document_billing_type == SKIP
        @summary_document_billing_type =
          summary_document_billing_type
      end
      unless summary_document_billing_type_id == SKIP
        @summary_document_billing_type_id =
          summary_document_billing_type_id
      end
      @summary_document_date = summary_document_date unless summary_document_date == SKIP
      unless summary_document_dd_amount == SKIP
        @summary_document_dd_amount =
          summary_document_dd_amount
      end
      unless summary_document_due_date == SKIP
        @summary_document_due_date =
          summary_document_due_date
      end
      @summary_document_id = summary_document_id unless summary_document_id == SKIP
      unless summary_document_is_fully_paid == SKIP
        @summary_document_is_fully_paid =
          summary_document_is_fully_paid
      end
      @summary_document_number = summary_document_number unless summary_document_number == SKIP
      unless summary_document_paid_amount == SKIP
        @summary_document_paid_amount =
          summary_document_paid_amount
      end
      unless summary_document_so_a_reference_number == SKIP
        @summary_document_so_a_reference_number =
          summary_document_so_a_reference_number
      end
      unless summary_document_statement_of_account_id == SKIP
        @summary_document_statement_of_account_id =
          summary_document_statement_of_account_id
      end
      unless transaction_currency_code == SKIP
        @transaction_currency_code =
          transaction_currency_code
      end
      unless transaction_currency_symbol == SKIP
        @transaction_currency_symbol =
          transaction_currency_symbol
      end
      @type = type unless type == SKIP
      @type_id = type_id unless type_id == SKIP
      unless vat_amount_customer_currency == SKIP
        @vat_amount_customer_currency =
          vat_amount_customer_currency
      end
      unless vat_amount_transaction_currency == SKIP
        @vat_amount_transaction_currency =
          vat_amount_transaction_currency
      end
      @vat_country = vat_country unless vat_country == SKIP
      @vat_country_id = vat_country_id unless vat_country_id == SKIP
      @vat_country_iso_code = vat_country_iso_code unless vat_country_iso_code == SKIP
      @vat_country_op_co_id = vat_country_op_co_id unless vat_country_op_co_id == SKIP
      @document_reference = document_reference unless document_reference == SKIP
      @additional_documents = additional_documents unless additional_documents == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_full_name =
        hash.key?('AccountFullName') ? hash['AccountFullName'] : SKIP
      account_id = hash.key?('AccountId') ? hash['AccountId'] : SKIP
      account_number = hash.key?('AccountNumber') ? hash['AccountNumber'] : SKIP
      account_short_name =
        hash.key?('AccountShortName') ? hash['AccountShortName'] : SKIP
      col_co_id = hash.key?('ColCoId') ? hash['ColCoId'] : SKIP
      col_co_op_co_id = hash.key?('ColCoOpCoId') ? hash['ColCoOpCoId'] : SKIP
      current_billing_frequency =
        hash.key?('CurrentBillingFrequency') ? hash['CurrentBillingFrequency'] : SKIP
      current_billing_frequency_id =
        hash.key?('CurrentBillingFrequencyId') ? hash['CurrentBillingFrequencyId'] : SKIP
      current_distribution_method =
        hash.key?('CurrentDistributionMethod') ? hash['CurrentDistributionMethod'] : SKIP
      current_distribution_method_id =
        hash.key?('CurrentDistributionMethodId') ? hash['CurrentDistributionMethodId'] : SKIP
      customer_currency_code =
        hash.key?('CustomerCurrencyCode') ? hash['CustomerCurrencyCode'] : SKIP
      customer_currency_symbol =
        hash.key?('CustomerCurrencySymbol') ? hash['CustomerCurrencySymbol'] : SKIP
      del_co_client_number =
        hash.key?('DelCoClientNumber') ? hash['DelCoClientNumber'] : SKIP
      del_co_id = hash.key?('DelCoId') ? hash['DelCoId'] : SKIP
      del_co_op_co_id = hash.key?('DelCoOpCoId') ? hash['DelCoOpCoId'] : SKIP
      document_type = hash.key?('DocumentType') ? hash['DocumentType'] : SKIP
      document_type_id =
        hash.key?('DocumentTypeId') ? hash['DocumentTypeId'] : SKIP
      due_date = hash.key?('DueDate') ? hash['DueDate'] : SKIP
      gross_amount_customer_currency =
        hash.key?('GrossAmountCustomerCurrency') ? hash['GrossAmountCustomerCurrency'] : SKIP
      gross_amount_transaction_currency =
        hash.key?('GrossAmountTransactionCurrency') ? hash['GrossAmountTransactionCurrency'] : SKIP
      invoice_date = hash.key?('InvoiceDate') ? hash['InvoiceDate'] : SKIP
      invoiced_by = hash.key?('InvoicedBy') ? hash['InvoicedBy'] : SKIP
      invoiced_on_behalf_of =
        hash.key?('InvoicedOnBehalfOf') ? hash['InvoicedOnBehalfOf'] : SKIP
      invoice_id = hash.key?('InvoiceId') ? hash['InvoiceId'] : SKIP
      invoice_number = hash.key?('InvoiceNumber') ? hash['InvoiceNumber'] : SKIP
      is_international =
        hash.key?('IsInternational') ? hash['IsInternational'] : SKIP
      is_national = hash.key?('IsNational') ? hash['IsNational'] : SKIP
      net_amount_customer_currency =
        hash.key?('NetAmountCustomerCurrency') ? hash['NetAmountCustomerCurrency'] : SKIP
      net_amount_transaction_currency =
        hash.key?('NetAmountTransactionCurrency') ? hash['NetAmountTransactionCurrency'] : SKIP
      payer_id = hash.key?('PayerId') ? hash['PayerId'] : SKIP
      payer_number = hash.key?('PayerNumber') ? hash['PayerNumber'] : SKIP
      payment_terms = hash.key?('PaymentTerms') ? hash['PaymentTerms'] : SKIP
      payment_terms_id =
        hash.key?('PaymentTermsId') ? hash['PaymentTermsId'] : SKIP
      replacement_invoice_id =
        hash.key?('ReplacementInvoiceId') ? hash['ReplacementInvoiceId'] : SKIP
      reversal_invoice_id =
        hash.key?('ReversalInvoiceId') ? hash['ReversalInvoiceId'] : SKIP
      status = hash.key?('Status') ? hash['Status'] : SKIP
      summary_document_billing_type =
        hash.key?('SummaryDocumentBillingType') ? hash['SummaryDocumentBillingType'] : SKIP
      summary_document_billing_type_id =
        hash.key?('SummaryDocumentBillingTypeId') ? hash['SummaryDocumentBillingTypeId'] : SKIP
      summary_document_date =
        hash.key?('SummaryDocumentDate') ? hash['SummaryDocumentDate'] : SKIP
      summary_document_dd_amount =
        hash.key?('SummaryDocumentDDAmount') ? hash['SummaryDocumentDDAmount'] : SKIP
      summary_document_due_date =
        hash.key?('SummaryDocumentDueDate') ? hash['SummaryDocumentDueDate'] : SKIP
      summary_document_id =
        hash.key?('SummaryDocumentId') ? hash['SummaryDocumentId'] : SKIP
      summary_document_is_fully_paid =
        hash.key?('SummaryDocumentIsFullyPaid') ? hash['SummaryDocumentIsFullyPaid'] : SKIP
      summary_document_number =
        hash.key?('SummaryDocumentNumber') ? hash['SummaryDocumentNumber'] : SKIP
      summary_document_paid_amount =
        hash.key?('SummaryDocumentPaidAmount') ? hash['SummaryDocumentPaidAmount'] : SKIP
      summary_document_so_a_reference_number =
        hash.key?('SummaryDocumentSoAReferenceNumber') ? hash['SummaryDocumentSoAReferenceNumber'] : SKIP
      summary_document_statement_of_account_id =
        hash.key?('SummaryDocumentStatementOfAccountId') ? hash['SummaryDocumentStatementOfAccountId'] : SKIP
      transaction_currency_code =
        hash.key?('TransactionCurrencyCode') ? hash['TransactionCurrencyCode'] : SKIP
      transaction_currency_symbol =
        hash.key?('TransactionCurrencySymbol') ? hash['TransactionCurrencySymbol'] : SKIP
      type = hash.key?('Type') ? hash['Type'] : SKIP
      type_id = hash.key?('TypeId') ? hash['TypeId'] : SKIP
      vat_amount_customer_currency =
        hash.key?('VATAmountCustomerCurrency') ? hash['VATAmountCustomerCurrency'] : SKIP
      vat_amount_transaction_currency =
        hash.key?('VATAmountTransactionCurrency') ? hash['VATAmountTransactionCurrency'] : SKIP
      vat_country = hash.key?('VATCountry') ? hash['VATCountry'] : SKIP
      vat_country_id = hash.key?('VATCountryId') ? hash['VATCountryId'] : SKIP
      vat_country_iso_code =
        hash.key?('VATCountryISOCode') ? hash['VATCountryISOCode'] : SKIP
      vat_country_op_co_id =
        hash.key?('VATCountryOpCoId') ? hash['VATCountryOpCoId'] : SKIP
      document_reference =
        hash.key?('DocumentReference') ? hash['DocumentReference'] : SKIP
      # Parameter is an array, so we need to iterate through it
      additional_documents = nil
      unless hash['AdditionalDocuments'].nil?
        additional_documents = []
        hash['AdditionalDocuments'].each do |structure|
          additional_documents << (InvoiceSearchAdditionalDocument.from_hash(structure) if structure)
        end
      end

      additional_documents = SKIP unless hash.key?('AdditionalDocuments')

      # Create object from extracted values.
      InvoiceSearchDetails.new(account_full_name,
                               account_id,
                               account_number,
                               account_short_name,
                               col_co_id,
                               col_co_op_co_id,
                               current_billing_frequency,
                               current_billing_frequency_id,
                               current_distribution_method,
                               current_distribution_method_id,
                               customer_currency_code,
                               customer_currency_symbol,
                               del_co_client_number,
                               del_co_id,
                               del_co_op_co_id,
                               document_type,
                               document_type_id,
                               due_date,
                               gross_amount_customer_currency,
                               gross_amount_transaction_currency,
                               invoice_date,
                               invoiced_by,
                               invoiced_on_behalf_of,
                               invoice_id,
                               invoice_number,
                               is_international,
                               is_national,
                               net_amount_customer_currency,
                               net_amount_transaction_currency,
                               payer_id,
                               payer_number,
                               payment_terms,
                               payment_terms_id,
                               replacement_invoice_id,
                               reversal_invoice_id,
                               status,
                               summary_document_billing_type,
                               summary_document_billing_type_id,
                               summary_document_date,
                               summary_document_dd_amount,
                               summary_document_due_date,
                               summary_document_id,
                               summary_document_is_fully_paid,
                               summary_document_number,
                               summary_document_paid_amount,
                               summary_document_so_a_reference_number,
                               summary_document_statement_of_account_id,
                               transaction_currency_code,
                               transaction_currency_symbol,
                               type,
                               type_id,
                               vat_amount_customer_currency,
                               vat_amount_transaction_currency,
                               vat_country,
                               vat_country_id,
                               vat_country_iso_code,
                               vat_country_op_co_id,
                               document_reference,
                               additional_documents)
    end
  end
end
