# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # MonthlyInvoiceTrend Model.
  class MonthlyInvoiceTrend < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # ISO code of invoice currency. 
    # Example: EUR
    # @return [String]
    attr_accessor :currency_code

    # Symbol of invoice currency. 
    # Example: €
    # @return [String]
    attr_accessor :currency_symbol

    # Month.
    # @return [Integer]
    attr_accessor :month

    # Total net amount invoiced in this month.
    # @return [Float]
    attr_accessor :total_net_amount

    # Total VAT amount invoiced in this month.
    # @return [Float]
    attr_accessor :total_vat_amount

    # Year.
    # @return [Integer]
    attr_accessor :year

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['currency_code'] = 'CurrencyCode'
      @_hash['currency_symbol'] = 'CurrencySymbol'
      @_hash['month'] = 'Month'
      @_hash['total_net_amount'] = 'TotalNetAmount'
      @_hash['total_vat_amount'] = 'TotalVATAmount'
      @_hash['year'] = 'Year'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        currency_code
        currency_symbol
        month
        total_net_amount
        total_vat_amount
        year
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        currency_code
        currency_symbol
        month
        total_net_amount
        total_vat_amount
        year
      ]
    end

    def initialize(currency_code = SKIP,
                   currency_symbol = SKIP,
                   month = SKIP,
                   total_net_amount = SKIP,
                   total_vat_amount = SKIP,
                   year = SKIP)
      @currency_code = currency_code unless currency_code == SKIP
      @currency_symbol = currency_symbol unless currency_symbol == SKIP
      @month = month unless month == SKIP
      @total_net_amount = total_net_amount unless total_net_amount == SKIP
      @total_vat_amount = total_vat_amount unless total_vat_amount == SKIP
      @year = year unless year == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      currency_code = hash.key?('CurrencyCode') ? hash['CurrencyCode'] : SKIP
      currency_symbol =
        hash.key?('CurrencySymbol') ? hash['CurrencySymbol'] : SKIP
      month = hash.key?('Month') ? hash['Month'] : SKIP
      total_net_amount =
        hash.key?('TotalNetAmount') ? hash['TotalNetAmount'] : SKIP
      total_vat_amount =
        hash.key?('TotalVATAmount') ? hash['TotalVATAmount'] : SKIP
      year = hash.key?('Year') ? hash['Year'] : SKIP

      # Create object from extracted values.
      MonthlyInvoiceTrend.new(currency_code,
                              currency_symbol,
                              month,
                              total_net_amount,
                              total_vat_amount,
                              year)
    end
  end
end
