# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # MultiPricedTransactionResponse Model.
  class MultiPricedTransactionResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[MultiPricedTransactionResponseTransactionsItems]]
    attr_accessor :transactions

    # TODO: Write general description for this method
    # @return [ErrorStatus]
    attr_accessor :error

    # API Request Id
    # @return [String]
    attr_accessor :request_id

    # Current Page
    # @return [Integer]
    attr_accessor :current_page

    # Total row count matched for the given input criteria
    # @return [Integer]
    attr_accessor :row_count

    # Calculated page count based on page size from the incoming API request and
    # total number of rows matched for the given input criteria
    # @return [Integer]
    attr_accessor :total_pages

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['transactions'] = 'Transactions'
      @_hash['error'] = 'Error'
      @_hash['request_id'] = 'RequestId'
      @_hash['current_page'] = 'CurrentPage'
      @_hash['row_count'] = 'RowCount'
      @_hash['total_pages'] = 'TotalPages'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        transactions
        error
        request_id
        current_page
        row_count
        total_pages
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(transactions = SKIP,
                   error = SKIP,
                   request_id = SKIP,
                   current_page = SKIP,
                   row_count = SKIP,
                   total_pages = SKIP)
      @transactions = transactions unless transactions == SKIP
      @error = error unless error == SKIP
      @request_id = request_id unless request_id == SKIP
      @current_page = current_page unless current_page == SKIP
      @row_count = row_count unless row_count == SKIP
      @total_pages = total_pages unless total_pages == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      transactions = nil
      unless hash['Transactions'].nil?
        transactions = []
        hash['Transactions'].each do |structure|
          transactions << (MultiPricedTransactionResponseTransactionsItems.from_hash(structure) if structure)
        end
      end

      transactions = SKIP unless hash.key?('Transactions')
      error = ErrorStatus.from_hash(hash['Error']) if hash['Error']
      request_id = hash.key?('RequestId') ? hash['RequestId'] : SKIP
      current_page = hash.key?('CurrentPage') ? hash['CurrentPage'] : SKIP
      row_count = hash.key?('RowCount') ? hash['RowCount'] : SKIP
      total_pages = hash.key?('TotalPages') ? hash['TotalPages'] : SKIP

      # Create object from extracted values.
      MultiPricedTransactionResponse.new(transactions,
                                         error,
                                         request_id,
                                         current_page,
                                         row_count,
                                         total_pages)
    end
  end
end
