# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # PayerResponse Model.
  class PayerResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Request Id of the API call
    # @return [String]
    attr_accessor :request_id

    # Request Id of the API call
    # @return [Array[PayerDetails]]
    attr_accessor :payers

    # Current Page
    # @return [Integer]
    attr_accessor :current_page

    # Total row count matched for the given input criteria
    # @return [Integer]
    attr_accessor :row_count

    # Calculated page count based on page size from the incoming API request and
    # total number of rows matched for the given input criteria. Return 1 if the
    # page size is -1 as all records are returned
    # @return [Integer]
    attr_accessor :total_pages

    # Calculated page count based on page size from the incoming API request and
    # total number of rows matched for the given input criteria. Return 1 if the
    # page size is -1 as all records are returned
    # @return [ErrorStatus]
    attr_accessor :error

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['request_id'] = 'RequestId'
      @_hash['payers'] = 'Payers'
      @_hash['current_page'] = 'CurrentPage'
      @_hash['row_count'] = 'RowCount'
      @_hash['total_pages'] = 'TotalPages'
      @_hash['error'] = 'Error'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        request_id
        payers
        current_page
        row_count
        total_pages
        error
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        request_id
      ]
    end

    def initialize(request_id = SKIP, payers = SKIP, current_page = SKIP,
                   row_count = SKIP, total_pages = SKIP, error = SKIP)
      @request_id = request_id unless request_id == SKIP
      @payers = payers unless payers == SKIP
      @current_page = current_page unless current_page == SKIP
      @row_count = row_count unless row_count == SKIP
      @total_pages = total_pages unless total_pages == SKIP
      @error = error unless error == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      request_id = hash.key?('RequestId') ? hash['RequestId'] : SKIP
      # Parameter is an array, so we need to iterate through it
      payers = nil
      unless hash['Payers'].nil?
        payers = []
        hash['Payers'].each do |structure|
          payers << (PayerDetails.from_hash(structure) if structure)
        end
      end

      payers = SKIP unless hash.key?('Payers')
      current_page = hash.key?('CurrentPage') ? hash['CurrentPage'] : SKIP
      row_count = hash.key?('RowCount') ? hash['RowCount'] : SKIP
      total_pages = hash.key?('TotalPages') ? hash['TotalPages'] : SKIP
      error = ErrorStatus.from_hash(hash['Error']) if hash['Error']

      # Create object from extracted values.
      PayerResponse.new(request_id,
                        payers,
                        current_page,
                        row_count,
                        total_pages,
                        error)
    end
  end
end
