# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # Invoice status of the transactions. Mandatory Possible options:I - Invoiced,
  # U – Un-Invoiced, A – All
  class PricedTransactionReqV2InvoiceStatusEnum
    PRICED_TRANSACTION_REQ_V2_INVOICE_STATUS_ENUM = [
      # TODO: Write general description for I
      I = 'I'.freeze,

      # TODO: Write general description for U
      U = 'U'.freeze,

      # TODO: Write general description for A
      A = 'A'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PRICED_TRANSACTION_REQ_V2_INVOICE_STATUS_ENUM.include?(value)
    end
  end
end
