# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # Allowed Sorting Options 1.    TransactionDateAscending 2.
  # TransactionDateDescending 3.    GrossAmountDescending 4.
  # GrossAmountAscending 5.    NetAmountAscending 6.    NetAmountDescensding
  class PricedTransactionReqV2SortOrderEnum
    PRICED_TRANSACTION_REQ_V2_SORT_ORDER_ENUM = [
      # TODO: Write general description for ENUM_1
      ENUM_1 = '1'.freeze,

      # TODO: Write general description for ENUM_2
      ENUM_2 = '2'.freeze,

      # TODO: Write general description for ENUM_3
      ENUM_3 = '3'.freeze,

      # TODO: Write general description for ENUM_4
      ENUM_4 = '4'.freeze,

      # TODO: Write general description for ENUM_5
      ENUM_5 = '5'.freeze,

      # TODO: Write general description for ENUM_6
      ENUM_6 = '6'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PRICED_TRANSACTION_REQ_V2_SORT_ORDER_ENUM.include?(value)
    end
  end
end
