# shell_data_reporting_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ShellDataReportingApIs
  # Allowed Sorting Options 1.    TransactionDateAscending 2.
  # TransactionDateDescending 3.    GrossAmountDescending 4.
  # GrossAmountAscending 5.    NetAmountAscending 6.    NetAmountDescensding
  class PricedTransactionReqV2SortOrderEnum
    PRICED_TRANSACTION_REQ_V2_SORT_ORDER_ENUM = [
      # TODO: Write general description for ENUM_1
      ENUM_1 = '1'.freeze,

      # TODO: Write general description for ENUM_2
      ENUM_2 = '2'.freeze,

      # TODO: Write general description for ENUM_3
      ENUM_3 = '3'.freeze,

      # TODO: Write general description for ENUM_4
      ENUM_4 = '4'.freeze,

      # TODO: Write general description for ENUM_5
      ENUM_5 = '5'.freeze,

      # TODO: Write general description for ENUM_6
      ENUM_6 = '6'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PRICED_TRANSACTION_REQ_V2_SORT_ORDER_ENUM.include?(value)
    end

    def self.from_value(value, default_value = ENUM_1)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'enum_1' then ENUM_1
      when 'enum_2' then ENUM_2
      when 'enum_3' then ENUM_3
      when 'enum_4' then ENUM_4
      when 'enum_5' then ENUM_5
      when 'enum_6' then ENUM_6
      else
        default_value
      end
    end
  end
end
