# shell_data_reporting_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ShellDataReportingApIs
  # Pass below one of the value as per the required transaction period 1. Last 7
  # Days 2. Last 30 Days 3. Last 90 Days
  class PricedTransactionReqV2PeriodEnum
    PRICED_TRANSACTION_REQ_V2_PERIOD_ENUM = [
      # TODO: Write general description for ENUM_1
      ENUM_1 = 1,

      # TODO: Write general description for ENUM_2
      ENUM_2 = 2,

      # TODO: Write general description for ENUM_3
      ENUM_3 = 3
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PRICED_TRANSACTION_REQ_V2_PERIOD_ENUM.include?(value)
    end

    def self.from_value(value, default_value = ENUM_1)
      return default_value if value.nil?

      str = value.to_s.strip
      if str.match?(/\A\d+\z/)
        num = str.to_i
        return num if PRICED_TRANSACTION_REQ_V2_PERIOD_ENUM.include?(num)

        return default_value
      end

      case str.downcase
      when 'enum_1' then ENUM_1
      when 'enum_2' then ENUM_2
      when 'enum_3' then ENUM_3
      else
        default_value
      end
    end
  end
end
