# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # RecentTransactionRequest Model.
  class RecentTransactionRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Specify the number of records to returned; Max 1000
    # @return [Integer]
    attr_accessor :page_size

    # Specify the page of results to be returned.
    # @return [Integer]
    attr_accessor :page

    # Specify the page of results to be returned.
    # @return [RecentTransactionReq]
    attr_accessor :filters

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['page_size'] = 'PageSize'
      @_hash['page'] = 'Page'
      @_hash['filters'] = 'Filters'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(page_size = nil, page = nil, filters = nil)
      @page_size = page_size
      @page = page
      @filters = filters
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      page_size = hash.key?('PageSize') ? hash['PageSize'] : nil
      page = hash.key?('Page') ? hash['Page'] : nil
      filters = RecentTransactionReq.from_hash(hash['Filters']) if hash['Filters']

      # Create object from extracted values.
      RecentTransactionRequest.new(page_size,
                                   page,
                                   filters)
    end
  end
end
