# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # TransactionExceptions Model.
  class TransactionExceptions < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Unique Sales Item Identifier
    # @return [Float]
    attr_accessor :sales_item_id

    # Unique Card Identifier
    # @return [Integer]
    attr_accessor :card_id

    # Product Id
    # @return [Integer]
    attr_accessor :product_id

    # Transaction Unique Identifier
    # @return [String]
    attr_accessor :transaction_guid

    # Local Transaction Date  of where the transaction took place
    # Format: yyyyMMdd
    # @return [String]
    attr_accessor :transaction_date

    # Total Gross Amount for the Invoice Customer
    # @return [Float]
    attr_accessor :customer_invoice_value_total_gross

    # Card PAN number
    # Returns masked PAN number when masking is enabled at the Microservices
    # configuration (Mask all digits except the last 6 digits of the PAN)
    # @return [String]
    attr_accessor :card_pan

    # Card Expiry Date
    # Format: yyyyMMdd
    # @return [String]
    attr_accessor :card_expiry

    # Local Transaction Time of where the transaction took place
    # Format: HH:mm:ss (24 hours format)
    # @return [String]
    attr_accessor :transaction_time

    # UTC Offset extracted from GFN Sales Date time. Note: This may not be
    # accurate for all TPN transactions
    # Format: +/-HH:mm:ss (24 hours format)
    # @return [String]
    attr_accessor :utc_offset

    # Fleet Id Input as entered by the drivers at the time of transaction
    # @return [String]
    attr_accessor :fleet_id_input

    # Odometer Input as entered by the drivers at the time of transaction
    # @return [Integer]
    attr_accessor :odometer_input

    # Driver Name embossed on the card
    # @return [String]
    attr_accessor :driver_name

    # Vehicle Registration Number embossed on the card
    # @return [String]
    attr_accessor :vehicle_registration

    # ISO currency code (Example: GBP)
    # @return [String]
    attr_accessor :invoice_currency_code

    # Currency symbol of the Invoice Currency Code (i.e. £, $, etc.,)
    # @return [String]
    attr_accessor :invoice_currency_symbol

    # ISO currency code
    # @return [String]
    attr_accessor :transaction_currency_code

    # Currency symbol of the Transaction Currency Code (i.e. £, $, etc.,)
    # @return [String]
    attr_accessor :transaction_currency_symbol

    # Net Amount
    # @return [Float]
    attr_accessor :transaction_net_amount

    # Tax Amount
    # @return [Float]
    attr_accessor :transaction_tax

    # Gross Amount
    # @return [Float]
    attr_accessor :transaction_gross_amount

    # Invoiced Net Amount
    # @return [Float]
    attr_accessor :invoice_net_amount

    # Invoiced Tax Amount
    # @return [Float]
    attr_accessor :invoice_tax

    # Invoice Gross Amount
    # @return [Float]
    attr_accessor :invoice_gross_amount

    # Country of Purchase (Ex: France, Germany, etc.,)
    # @return [String]
    attr_accessor :purchased_in_country

    # Account Id
    # @return [Integer]
    attr_accessor :account_id

    # Account Number
    # @return [String]
    attr_accessor :account_number

    # Account Name
    # @return [String]
    attr_accessor :account_name

    # Account Short Name
    # @return [String]
    attr_accessor :account_short_name

    # Quantity/Volume
    # @return [Float]
    attr_accessor :quantity

    # True if the product on transaction is listed as a fuel product else return
    # false
    # @return [TrueClass | FalseClass]
    attr_accessor :fuel_product

    # Product Unit Price in transaction currency
    # @return [Float]
    attr_accessor :unit_price_in_transaction_currency

    # Product Unit Price in invoice currency
    # @return [Float]
    attr_accessor :unit_price_in_invoice_currency

    # Unit Discount in transaction currency
    # @return [Float]
    attr_accessor :unit_discount_transaction_currency

    # Unit Discount in invoice currency
    # @return [Float]
    attr_accessor :unit_discount_invoice_currency

    # True when the transaction is already invoice, else return False
    # @return [TrueClass | FalseClass]
    attr_accessor :is_invoiced

    # Invoice Number if invoiced
    # @return [String]
    attr_accessor :invoice_number

    # Invoice Date 
    # Format: yyyyMMdd HH:mm:ss
    # @return [String]
    attr_accessor :invoice_date

    # Site Code
    # @return [String]
    attr_accessor :site_code

    # Site Name
    # @return [String]
    attr_accessor :site_name

    # Site Country
    # @return [String]
    attr_accessor :site_country

    # Geography Location entity for Site Location
    # @return [ExceptionSiteLocation]
    attr_accessor :location

    # Card Group Name
    # @return [String]
    attr_accessor :card_group_name

    # Receipt Number
    # @return [String]
    attr_accessor :receipt_number

    # Product Code
    # @return [String]
    attr_accessor :product_code

    # Product Name
    # @return [String]
    attr_accessor :product_name

    # Product Group Id
    # @return [Integer]
    attr_accessor :product_group_id

    # Product Group Name
    # @return [String]
    attr_accessor :product_group_name

    # DelCo Exchange Rate (Site exchange rate)
    # @return [Float]
    attr_accessor :del_co_exchange_rate

    # ColCo Exchange Rate (Customer exchange rate)
    # @return [Float]
    attr_accessor :col_co_exchange_rate

    # True when transaction occurred at a Shell site else return False
    # @return [TrueClass | FalseClass]
    attr_accessor :is_shell_site

    # Network as configured
    # @return [String]
    attr_accessor :network

    # Site Group Id
    # @return [Integer]
    attr_accessor :site_group_id

    # Site GroupName
    # @return [String]
    attr_accessor :site_group_name

    # Site GroupName
    # @return [String]
    attr_accessor :posting_date

    # First digits of the Card PAN 
    # 7002 = Fleet  
    # 7077 = CRT
    # @return [String]
    attr_accessor :issuer_code

    # ISO code of the country where the transaction took place
    # @return [String]
    attr_accessor :purchased_in_country_code

    # ISO code of the  Customer Country
    # @return [String]
    attr_accessor :customer_country_code

    # Name of the Customer Country
    # @return [String]
    attr_accessor :customer_country

    # Release code, 7th Digit of the Card PAN
    # @return [String]
    attr_accessor :release_code

    # Card group ID
    # @return [String]
    attr_accessor :card_group_id

    # 3 digits, Card sequence number and Check digit  (Digit 16,17 and 18 on the
    # card pan)
    # @return [String]
    attr_accessor :card_sequence_number

    # Check digit, Last number of the card pan
    # @return [String]
    attr_accessor :check_digit

    # FleetId/CRN description in Card Platform configured at the account level
    # @return [String]
    attr_accessor :fleet_id_description

    # VAT Percentage
    # @return [Float]
    attr_accessor :vat_rate

    # VAT Category Id-Description
    # 1-Zero Rated
    # 2-A1 PH-O 12% Sales Domestic
    # 3-VAT exempt
    # @return [String]
    attr_accessor :vat_category

    # Effective Discount (excluding VAT, in transaction currency)  4 digits
    # @return [String]
    attr_accessor :effective_discount_in_trx_currency

    # Transaction Type
    # @return [String]
    attr_accessor :transaction_type

    # Pin Indicator (Indicates whether PIN used or not used at the time of
    # transaction)
    # @return [String]
    attr_accessor :pin_indicator

    # Is VAT Applicable for this transaction
    # “Y” or “N”
    # @return [String]
    attr_accessor :vat_applicable

    # Net Invoice Indicator, Will the customer receive an invoice without VAT?
    # Example: “Y” or “N”
    # @return [String]
    attr_accessor :net_invoice_indicator

    # Customer currency code
    # @return [String]
    attr_accessor :customer_currency_code

    # Customer currency Symbol
    # @return [String]
    attr_accessor :customer_currency_symbol

    # Effective Unit Discount
    # @return [Float]
    attr_accessor :effective_unit_discount_in_customer_currency

    # Effective Discount
    # @return [Float]
    attr_accessor :effective_discount_in_customer_currency

    # VAT on Net Amount
    # @return [Float]
    attr_accessor :va_ton_net_amount_in_customer_currency

    # Discount Type
    # Example: 1-None
    # 2-Pence per unit
    # 3-Percentage
    # @return [String]
    attr_accessor :discount_type

    # Transaction status  "U" or "I"
    # “U” stands for Uninvoiced
    # “I” stands for Invoiced
    # @return [String]
    attr_accessor :transaction_status

    # Payer Group applicable for the Large Customer NL+8 digit code
    # @return [String]
    attr_accessor :payer_group

    # Refund Flag “N” for Not Refunded and “Y” for Refunded.
    # @return [String]
    attr_accessor :refund_flag

    # Shows Sales Item Id of the original item that was refunded
    # @return [Float]
    attr_accessor :original_sales_item_id

    # Delco Name
    # @return [String]
    attr_accessor :delco_name

    # Delco Code
    # @return [String]
    attr_accessor :delco_code

    # Payer number
    # @return [String]
    attr_accessor :payer_number

    # Payer name
    # @return [String]
    attr_accessor :payer_name

    # Year/Month of the Card Expiry captured on the transaction
    # @return [String]
    attr_accessor :card_expiry_period

    # Authorisation code of the transaction
    # @return [String]
    attr_accessor :authorisation_code

    # Unique id of the transaction that may include one or more salesitems
    # @return [String]
    attr_accessor :transaction_id

    # Transaction line item number
    # @return [String]
    attr_accessor :transaction_line

    # Is the Sales Item allowed for clearing? i.e. not written off
    # Example: “Y” or “N”
    # @return [String]
    attr_accessor :allow_clearing

    # CRM Case number if the sales item is in dispute
    # @return [String]
    attr_accessor :crm_number

    # Sales Item Dispute Status if disputed
    # 0	No Dispute
    # 1	In Dispute
    # 2	Re-Instated
    # 3	Adjusted
    # 4	Written Off by Colco
    # 5	Written Off by Delco
    # 6	Charged Back to Site
    # @return [String]
    attr_accessor :dispute_status

    # Unit discount in customer currency
    # @return [Float]
    attr_accessor :rebate_rate

    # Exchange rate from transaction currency to customer currency.
    # @return [Float]
    attr_accessor :del_co_to_col_co_exchange_rate

    # Net euro amount.
    # @return [Float]
    attr_accessor :net_euro_amount

    # Euro rebate amount.
    # @return [Float]
    attr_accessor :euro_rebate_amount

    # Euro VAT amount.
    # @return [Float]
    attr_accessor :euro_vat_amount

    # Parent customer number
    # @return [String]
    attr_accessor :parent_customer_number

    # VAT on Net Amount (in transaction currency) 2 decimals
    # @return [Float]
    attr_accessor :va_ton_net_amount

    # VAT Country
    # @return [String]
    attr_accessor :vat_country

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['sales_item_id'] = 'SalesItemId'
      @_hash['card_id'] = 'CardId'
      @_hash['product_id'] = 'ProductId'
      @_hash['transaction_guid'] = 'TransactionGUID'
      @_hash['transaction_date'] = 'TransactionDate'
      @_hash['customer_invoice_value_total_gross'] =
        'CustomerInvoiceValueTotalGross'
      @_hash['card_pan'] = 'CardPAN'
      @_hash['card_expiry'] = 'CardExpiry'
      @_hash['transaction_time'] = 'TransactionTime'
      @_hash['utc_offset'] = 'UTCOffset'
      @_hash['fleet_id_input'] = 'FleetIdInput'
      @_hash['odometer_input'] = 'OdometerInput'
      @_hash['driver_name'] = 'DriverName'
      @_hash['vehicle_registration'] = 'VehicleRegistration'
      @_hash['invoice_currency_code'] = 'InvoiceCurrencyCode'
      @_hash['invoice_currency_symbol'] = 'InvoiceCurrencySymbol'
      @_hash['transaction_currency_code'] = 'TransactionCurrencyCode'
      @_hash['transaction_currency_symbol'] = 'TransactionCurrencySymbol'
      @_hash['transaction_net_amount'] = 'TransactionNetAmount'
      @_hash['transaction_tax'] = 'TransactionTax'
      @_hash['transaction_gross_amount'] = 'TransactionGrossAmount'
      @_hash['invoice_net_amount'] = 'InvoiceNetAmount'
      @_hash['invoice_tax'] = 'InvoiceTax'
      @_hash['invoice_gross_amount'] = 'InvoiceGrossAmount'
      @_hash['purchased_in_country'] = 'PurchasedInCountry'
      @_hash['account_id'] = 'AccountId'
      @_hash['account_number'] = 'AccountNumber'
      @_hash['account_name'] = 'AccountName'
      @_hash['account_short_name'] = 'AccountShortName'
      @_hash['quantity'] = 'Quantity'
      @_hash['fuel_product'] = 'FuelProduct'
      @_hash['unit_price_in_transaction_currency'] =
        'UnitPriceInTransactionCurrency'
      @_hash['unit_price_in_invoice_currency'] = 'UnitPriceInInvoiceCurrency'
      @_hash['unit_discount_transaction_currency'] =
        'UnitDiscountTransactionCurrency'
      @_hash['unit_discount_invoice_currency'] = 'UnitDiscountInvoiceCurrency'
      @_hash['is_invoiced'] = 'IsInvoiced'
      @_hash['invoice_number'] = 'InvoiceNumber'
      @_hash['invoice_date'] = 'InvoiceDate'
      @_hash['site_code'] = 'SiteCode'
      @_hash['site_name'] = 'SiteName'
      @_hash['site_country'] = 'SiteCountry'
      @_hash['location'] = 'Location'
      @_hash['card_group_name'] = 'CardGroupName'
      @_hash['receipt_number'] = 'ReceiptNumber'
      @_hash['product_code'] = 'ProductCode'
      @_hash['product_name'] = 'ProductName'
      @_hash['product_group_id'] = 'ProductGroupId'
      @_hash['product_group_name'] = 'ProductGroupName'
      @_hash['del_co_exchange_rate'] = 'DelCoExchangeRate'
      @_hash['col_co_exchange_rate'] = 'ColCoExchangeRate'
      @_hash['is_shell_site'] = 'IsShellSite'
      @_hash['network'] = 'Network'
      @_hash['site_group_id'] = 'SiteGroupId'
      @_hash['site_group_name'] = 'SiteGroupName'
      @_hash['posting_date'] = 'PostingDate'
      @_hash['issuer_code'] = 'IssuerCode'
      @_hash['purchased_in_country_code'] = 'PurchasedInCountryCode'
      @_hash['customer_country_code'] = 'CustomerCountryCode'
      @_hash['customer_country'] = 'CustomerCountry'
      @_hash['release_code'] = 'ReleaseCode'
      @_hash['card_group_id'] = 'CardGroupId'
      @_hash['card_sequence_number'] = 'CardSequenceNumber'
      @_hash['check_digit'] = 'CheckDigit'
      @_hash['fleet_id_description'] = 'FleetIDDescription'
      @_hash['vat_rate'] = 'VATRate'
      @_hash['vat_category'] = 'VATCategory'
      @_hash['effective_discount_in_trx_currency'] =
        'EffectiveDiscountInTrxCurrency'
      @_hash['transaction_type'] = 'TransactionType'
      @_hash['pin_indicator'] = 'PINIndicator'
      @_hash['vat_applicable'] = 'VATApplicable'
      @_hash['net_invoice_indicator'] = 'NetInvoiceIndicator'
      @_hash['customer_currency_code'] = 'CustomerCurrencyCode'
      @_hash['customer_currency_symbol'] = 'CustomerCurrencySymbol'
      @_hash['effective_unit_discount_in_customer_currency'] =
        'EffectiveUnitDiscountInCustomerCurrency'
      @_hash['effective_discount_in_customer_currency'] =
        'EffectiveDiscountInCustomerCurrency'
      @_hash['va_ton_net_amount_in_customer_currency'] =
        'VATonNetAmountInCustomerCurrency'
      @_hash['discount_type'] = 'DiscountType'
      @_hash['transaction_status'] = 'TransactionStatus'
      @_hash['payer_group'] = 'PayerGroup'
      @_hash['refund_flag'] = 'RefundFlag'
      @_hash['original_sales_item_id'] = 'OriginalSalesItemId'
      @_hash['delco_name'] = 'DelcoName'
      @_hash['delco_code'] = 'DelcoCode'
      @_hash['payer_number'] = 'PayerNumber'
      @_hash['payer_name'] = 'PayerName'
      @_hash['card_expiry_period'] = 'CardExpiryPeriod'
      @_hash['authorisation_code'] = 'AuthorisationCode'
      @_hash['transaction_id'] = 'TransactionId'
      @_hash['transaction_line'] = 'TransactionLine'
      @_hash['allow_clearing'] = 'AllowClearing'
      @_hash['crm_number'] = 'CRMNumber'
      @_hash['dispute_status'] = 'DisputeStatus'
      @_hash['rebate_rate'] = 'RebateRate'
      @_hash['del_co_to_col_co_exchange_rate'] = 'DelCoToColCoExchangeRate'
      @_hash['net_euro_amount'] = 'NetEuroAmount'
      @_hash['euro_rebate_amount'] = 'EuroRebateAmount'
      @_hash['euro_vat_amount'] = 'EuroVATAmount'
      @_hash['parent_customer_number'] = 'ParentCustomerNumber'
      @_hash['va_ton_net_amount'] = 'VATonNetAmount'
      @_hash['vat_country'] = 'VATCountry'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        sales_item_id
        card_id
        product_id
        transaction_guid
        transaction_date
        customer_invoice_value_total_gross
        card_pan
        card_expiry
        transaction_time
        utc_offset
        fleet_id_input
        odometer_input
        driver_name
        vehicle_registration
        invoice_currency_code
        invoice_currency_symbol
        transaction_currency_code
        transaction_currency_symbol
        transaction_net_amount
        transaction_tax
        transaction_gross_amount
        invoice_net_amount
        invoice_tax
        invoice_gross_amount
        purchased_in_country
        account_id
        account_number
        account_name
        account_short_name
        quantity
        fuel_product
        unit_price_in_transaction_currency
        unit_price_in_invoice_currency
        unit_discount_transaction_currency
        unit_discount_invoice_currency
        is_invoiced
        invoice_number
        invoice_date
        site_code
        site_name
        site_country
        location
        card_group_name
        receipt_number
        product_code
        product_name
        product_group_id
        product_group_name
        del_co_exchange_rate
        col_co_exchange_rate
        is_shell_site
        network
        site_group_id
        site_group_name
        posting_date
        issuer_code
        purchased_in_country_code
        customer_country_code
        customer_country
        release_code
        card_group_id
        card_sequence_number
        check_digit
        fleet_id_description
        vat_rate
        vat_category
        effective_discount_in_trx_currency
        transaction_type
        pin_indicator
        vat_applicable
        net_invoice_indicator
        customer_currency_code
        customer_currency_symbol
        effective_unit_discount_in_customer_currency
        effective_discount_in_customer_currency
        va_ton_net_amount_in_customer_currency
        discount_type
        transaction_status
        payer_group
        refund_flag
        original_sales_item_id
        delco_name
        delco_code
        payer_number
        payer_name
        card_expiry_period
        authorisation_code
        transaction_id
        transaction_line
        allow_clearing
        crm_number
        dispute_status
        rebate_rate
        del_co_to_col_co_exchange_rate
        net_euro_amount
        euro_rebate_amount
        euro_vat_amount
        parent_customer_number
        va_ton_net_amount
        vat_country
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        sales_item_id
        card_id
        product_id
        transaction_guid
        transaction_date
        customer_invoice_value_total_gross
        card_pan
        card_expiry
        transaction_time
        utc_offset
        fleet_id_input
        odometer_input
        driver_name
        vehicle_registration
        invoice_currency_code
        invoice_currency_symbol
        transaction_currency_code
        transaction_currency_symbol
        transaction_net_amount
        transaction_tax
        transaction_gross_amount
        invoice_net_amount
        invoice_tax
        invoice_gross_amount
        purchased_in_country
        account_id
        account_number
        account_name
        account_short_name
        quantity
        fuel_product
        unit_price_in_transaction_currency
        unit_price_in_invoice_currency
        unit_discount_transaction_currency
        unit_discount_invoice_currency
        is_invoiced
        invoice_number
        invoice_date
        site_code
        site_name
        site_country
        card_group_name
        receipt_number
        product_code
        product_name
        product_group_id
        product_group_name
        del_co_exchange_rate
        col_co_exchange_rate
        is_shell_site
        network
        site_group_id
        site_group_name
        posting_date
        issuer_code
        purchased_in_country_code
        customer_country_code
        customer_country
        release_code
        card_group_id
        card_sequence_number
        check_digit
        fleet_id_description
        vat_rate
        vat_category
        effective_discount_in_trx_currency
        transaction_type
        pin_indicator
        vat_applicable
        net_invoice_indicator
        customer_currency_code
        customer_currency_symbol
        effective_unit_discount_in_customer_currency
        effective_discount_in_customer_currency
        va_ton_net_amount_in_customer_currency
        discount_type
        transaction_status
        payer_group
        refund_flag
        original_sales_item_id
        delco_name
        delco_code
        payer_number
        payer_name
        card_expiry_period
        authorisation_code
        transaction_id
        transaction_line
        allow_clearing
        crm_number
        dispute_status
        rebate_rate
        del_co_to_col_co_exchange_rate
        net_euro_amount
        euro_rebate_amount
        euro_vat_amount
        parent_customer_number
        va_ton_net_amount
        vat_country
      ]
    end

    def initialize(sales_item_id = SKIP,
                   card_id = SKIP,
                   product_id = SKIP,
                   transaction_guid = SKIP,
                   transaction_date = SKIP,
                   customer_invoice_value_total_gross = SKIP,
                   card_pan = SKIP,
                   card_expiry = SKIP,
                   transaction_time = SKIP,
                   utc_offset = SKIP,
                   fleet_id_input = SKIP,
                   odometer_input = SKIP,
                   driver_name = SKIP,
                   vehicle_registration = SKIP,
                   invoice_currency_code = SKIP,
                   invoice_currency_symbol = SKIP,
                   transaction_currency_code = SKIP,
                   transaction_currency_symbol = SKIP,
                   transaction_net_amount = SKIP,
                   transaction_tax = SKIP,
                   transaction_gross_amount = SKIP,
                   invoice_net_amount = SKIP,
                   invoice_tax = SKIP,
                   invoice_gross_amount = SKIP,
                   purchased_in_country = SKIP,
                   account_id = SKIP,
                   account_number = SKIP,
                   account_name = SKIP,
                   account_short_name = SKIP,
                   quantity = SKIP,
                   fuel_product = SKIP,
                   unit_price_in_transaction_currency = SKIP,
                   unit_price_in_invoice_currency = SKIP,
                   unit_discount_transaction_currency = SKIP,
                   unit_discount_invoice_currency = SKIP,
                   is_invoiced = SKIP,
                   invoice_number = SKIP,
                   invoice_date = SKIP,
                   site_code = SKIP,
                   site_name = SKIP,
                   site_country = SKIP,
                   location = SKIP,
                   card_group_name = SKIP,
                   receipt_number = SKIP,
                   product_code = SKIP,
                   product_name = SKIP,
                   product_group_id = SKIP,
                   product_group_name = SKIP,
                   del_co_exchange_rate = SKIP,
                   col_co_exchange_rate = SKIP,
                   is_shell_site = SKIP,
                   network = SKIP,
                   site_group_id = SKIP,
                   site_group_name = SKIP,
                   posting_date = SKIP,
                   issuer_code = SKIP,
                   purchased_in_country_code = SKIP,
                   customer_country_code = SKIP,
                   customer_country = SKIP,
                   release_code = SKIP,
                   card_group_id = SKIP,
                   card_sequence_number = SKIP,
                   check_digit = SKIP,
                   fleet_id_description = SKIP,
                   vat_rate = SKIP,
                   vat_category = SKIP,
                   effective_discount_in_trx_currency = SKIP,
                   transaction_type = SKIP,
                   pin_indicator = SKIP,
                   vat_applicable = SKIP,
                   net_invoice_indicator = SKIP,
                   customer_currency_code = SKIP,
                   customer_currency_symbol = SKIP,
                   effective_unit_discount_in_customer_currency = SKIP,
                   effective_discount_in_customer_currency = SKIP,
                   va_ton_net_amount_in_customer_currency = SKIP,
                   discount_type = SKIP,
                   transaction_status = SKIP,
                   payer_group = SKIP,
                   refund_flag = SKIP,
                   original_sales_item_id = SKIP,
                   delco_name = SKIP,
                   delco_code = SKIP,
                   payer_number = SKIP,
                   payer_name = SKIP,
                   card_expiry_period = SKIP,
                   authorisation_code = SKIP,
                   transaction_id = SKIP,
                   transaction_line = SKIP,
                   allow_clearing = SKIP,
                   crm_number = SKIP,
                   dispute_status = SKIP,
                   rebate_rate = SKIP,
                   del_co_to_col_co_exchange_rate = SKIP,
                   net_euro_amount = SKIP,
                   euro_rebate_amount = SKIP,
                   euro_vat_amount = SKIP,
                   parent_customer_number = SKIP,
                   va_ton_net_amount = SKIP,
                   vat_country = SKIP)
      @sales_item_id = sales_item_id unless sales_item_id == SKIP
      @card_id = card_id unless card_id == SKIP
      @product_id = product_id unless product_id == SKIP
      @transaction_guid = transaction_guid unless transaction_guid == SKIP
      @transaction_date = transaction_date unless transaction_date == SKIP
      unless customer_invoice_value_total_gross == SKIP
        @customer_invoice_value_total_gross =
          customer_invoice_value_total_gross
      end
      @card_pan = card_pan unless card_pan == SKIP
      @card_expiry = card_expiry unless card_expiry == SKIP
      @transaction_time = transaction_time unless transaction_time == SKIP
      @utc_offset = utc_offset unless utc_offset == SKIP
      @fleet_id_input = fleet_id_input unless fleet_id_input == SKIP
      @odometer_input = odometer_input unless odometer_input == SKIP
      @driver_name = driver_name unless driver_name == SKIP
      @vehicle_registration = vehicle_registration unless vehicle_registration == SKIP
      @invoice_currency_code = invoice_currency_code unless invoice_currency_code == SKIP
      @invoice_currency_symbol = invoice_currency_symbol unless invoice_currency_symbol == SKIP
      unless transaction_currency_code == SKIP
        @transaction_currency_code =
          transaction_currency_code
      end
      unless transaction_currency_symbol == SKIP
        @transaction_currency_symbol =
          transaction_currency_symbol
      end
      @transaction_net_amount = transaction_net_amount unless transaction_net_amount == SKIP
      @transaction_tax = transaction_tax unless transaction_tax == SKIP
      @transaction_gross_amount = transaction_gross_amount unless transaction_gross_amount == SKIP
      @invoice_net_amount = invoice_net_amount unless invoice_net_amount == SKIP
      @invoice_tax = invoice_tax unless invoice_tax == SKIP
      @invoice_gross_amount = invoice_gross_amount unless invoice_gross_amount == SKIP
      @purchased_in_country = purchased_in_country unless purchased_in_country == SKIP
      @account_id = account_id unless account_id == SKIP
      @account_number = account_number unless account_number == SKIP
      @account_name = account_name unless account_name == SKIP
      @account_short_name = account_short_name unless account_short_name == SKIP
      @quantity = quantity unless quantity == SKIP
      @fuel_product = fuel_product unless fuel_product == SKIP
      unless unit_price_in_transaction_currency == SKIP
        @unit_price_in_transaction_currency =
          unit_price_in_transaction_currency
      end
      unless unit_price_in_invoice_currency == SKIP
        @unit_price_in_invoice_currency =
          unit_price_in_invoice_currency
      end
      unless unit_discount_transaction_currency == SKIP
        @unit_discount_transaction_currency =
          unit_discount_transaction_currency
      end
      unless unit_discount_invoice_currency == SKIP
        @unit_discount_invoice_currency =
          unit_discount_invoice_currency
      end
      @is_invoiced = is_invoiced unless is_invoiced == SKIP
      @invoice_number = invoice_number unless invoice_number == SKIP
      @invoice_date = invoice_date unless invoice_date == SKIP
      @site_code = site_code unless site_code == SKIP
      @site_name = site_name unless site_name == SKIP
      @site_country = site_country unless site_country == SKIP
      @location = location unless location == SKIP
      @card_group_name = card_group_name unless card_group_name == SKIP
      @receipt_number = receipt_number unless receipt_number == SKIP
      @product_code = product_code unless product_code == SKIP
      @product_name = product_name unless product_name == SKIP
      @product_group_id = product_group_id unless product_group_id == SKIP
      @product_group_name = product_group_name unless product_group_name == SKIP
      @del_co_exchange_rate = del_co_exchange_rate unless del_co_exchange_rate == SKIP
      @col_co_exchange_rate = col_co_exchange_rate unless col_co_exchange_rate == SKIP
      @is_shell_site = is_shell_site unless is_shell_site == SKIP
      @network = network unless network == SKIP
      @site_group_id = site_group_id unless site_group_id == SKIP
      @site_group_name = site_group_name unless site_group_name == SKIP
      @posting_date = posting_date unless posting_date == SKIP
      @issuer_code = issuer_code unless issuer_code == SKIP
      unless purchased_in_country_code == SKIP
        @purchased_in_country_code =
          purchased_in_country_code
      end
      @customer_country_code = customer_country_code unless customer_country_code == SKIP
      @customer_country = customer_country unless customer_country == SKIP
      @release_code = release_code unless release_code == SKIP
      @card_group_id = card_group_id unless card_group_id == SKIP
      @card_sequence_number = card_sequence_number unless card_sequence_number == SKIP
      @check_digit = check_digit unless check_digit == SKIP
      @fleet_id_description = fleet_id_description unless fleet_id_description == SKIP
      @vat_rate = vat_rate unless vat_rate == SKIP
      @vat_category = vat_category unless vat_category == SKIP
      unless effective_discount_in_trx_currency == SKIP
        @effective_discount_in_trx_currency =
          effective_discount_in_trx_currency
      end
      @transaction_type = transaction_type unless transaction_type == SKIP
      @pin_indicator = pin_indicator unless pin_indicator == SKIP
      @vat_applicable = vat_applicable unless vat_applicable == SKIP
      @net_invoice_indicator = net_invoice_indicator unless net_invoice_indicator == SKIP
      @customer_currency_code = customer_currency_code unless customer_currency_code == SKIP
      @customer_currency_symbol = customer_currency_symbol unless customer_currency_symbol == SKIP
      unless effective_unit_discount_in_customer_currency == SKIP
        @effective_unit_discount_in_customer_currency =
          effective_unit_discount_in_customer_currency
      end
      unless effective_discount_in_customer_currency == SKIP
        @effective_discount_in_customer_currency =
          effective_discount_in_customer_currency
      end
      unless va_ton_net_amount_in_customer_currency == SKIP
        @va_ton_net_amount_in_customer_currency =
          va_ton_net_amount_in_customer_currency
      end
      @discount_type = discount_type unless discount_type == SKIP
      @transaction_status = transaction_status unless transaction_status == SKIP
      @payer_group = payer_group unless payer_group == SKIP
      @refund_flag = refund_flag unless refund_flag == SKIP
      @original_sales_item_id = original_sales_item_id unless original_sales_item_id == SKIP
      @delco_name = delco_name unless delco_name == SKIP
      @delco_code = delco_code unless delco_code == SKIP
      @payer_number = payer_number unless payer_number == SKIP
      @payer_name = payer_name unless payer_name == SKIP
      @card_expiry_period = card_expiry_period unless card_expiry_period == SKIP
      @authorisation_code = authorisation_code unless authorisation_code == SKIP
      @transaction_id = transaction_id unless transaction_id == SKIP
      @transaction_line = transaction_line unless transaction_line == SKIP
      @allow_clearing = allow_clearing unless allow_clearing == SKIP
      @crm_number = crm_number unless crm_number == SKIP
      @dispute_status = dispute_status unless dispute_status == SKIP
      @rebate_rate = rebate_rate unless rebate_rate == SKIP
      unless del_co_to_col_co_exchange_rate == SKIP
        @del_co_to_col_co_exchange_rate =
          del_co_to_col_co_exchange_rate
      end
      @net_euro_amount = net_euro_amount unless net_euro_amount == SKIP
      @euro_rebate_amount = euro_rebate_amount unless euro_rebate_amount == SKIP
      @euro_vat_amount = euro_vat_amount unless euro_vat_amount == SKIP
      @parent_customer_number = parent_customer_number unless parent_customer_number == SKIP
      @va_ton_net_amount = va_ton_net_amount unless va_ton_net_amount == SKIP
      @vat_country = vat_country unless vat_country == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      sales_item_id = hash.key?('SalesItemId') ? hash['SalesItemId'] : SKIP
      card_id = hash.key?('CardId') ? hash['CardId'] : SKIP
      product_id = hash.key?('ProductId') ? hash['ProductId'] : SKIP
      transaction_guid =
        hash.key?('TransactionGUID') ? hash['TransactionGUID'] : SKIP
      transaction_date =
        hash.key?('TransactionDate') ? hash['TransactionDate'] : SKIP
      customer_invoice_value_total_gross =
        hash.key?('CustomerInvoiceValueTotalGross') ? hash['CustomerInvoiceValueTotalGross'] : SKIP
      card_pan = hash.key?('CardPAN') ? hash['CardPAN'] : SKIP
      card_expiry = hash.key?('CardExpiry') ? hash['CardExpiry'] : SKIP
      transaction_time =
        hash.key?('TransactionTime') ? hash['TransactionTime'] : SKIP
      utc_offset = hash.key?('UTCOffset') ? hash['UTCOffset'] : SKIP
      fleet_id_input = hash.key?('FleetIdInput') ? hash['FleetIdInput'] : SKIP
      odometer_input = hash.key?('OdometerInput') ? hash['OdometerInput'] : SKIP
      driver_name = hash.key?('DriverName') ? hash['DriverName'] : SKIP
      vehicle_registration =
        hash.key?('VehicleRegistration') ? hash['VehicleRegistration'] : SKIP
      invoice_currency_code =
        hash.key?('InvoiceCurrencyCode') ? hash['InvoiceCurrencyCode'] : SKIP
      invoice_currency_symbol =
        hash.key?('InvoiceCurrencySymbol') ? hash['InvoiceCurrencySymbol'] : SKIP
      transaction_currency_code =
        hash.key?('TransactionCurrencyCode') ? hash['TransactionCurrencyCode'] : SKIP
      transaction_currency_symbol =
        hash.key?('TransactionCurrencySymbol') ? hash['TransactionCurrencySymbol'] : SKIP
      transaction_net_amount =
        hash.key?('TransactionNetAmount') ? hash['TransactionNetAmount'] : SKIP
      transaction_tax =
        hash.key?('TransactionTax') ? hash['TransactionTax'] : SKIP
      transaction_gross_amount =
        hash.key?('TransactionGrossAmount') ? hash['TransactionGrossAmount'] : SKIP
      invoice_net_amount =
        hash.key?('InvoiceNetAmount') ? hash['InvoiceNetAmount'] : SKIP
      invoice_tax = hash.key?('InvoiceTax') ? hash['InvoiceTax'] : SKIP
      invoice_gross_amount =
        hash.key?('InvoiceGrossAmount') ? hash['InvoiceGrossAmount'] : SKIP
      purchased_in_country =
        hash.key?('PurchasedInCountry') ? hash['PurchasedInCountry'] : SKIP
      account_id = hash.key?('AccountId') ? hash['AccountId'] : SKIP
      account_number = hash.key?('AccountNumber') ? hash['AccountNumber'] : SKIP
      account_name = hash.key?('AccountName') ? hash['AccountName'] : SKIP
      account_short_name =
        hash.key?('AccountShortName') ? hash['AccountShortName'] : SKIP
      quantity = hash.key?('Quantity') ? hash['Quantity'] : SKIP
      fuel_product = hash.key?('FuelProduct') ? hash['FuelProduct'] : SKIP
      unit_price_in_transaction_currency =
        hash.key?('UnitPriceInTransactionCurrency') ? hash['UnitPriceInTransactionCurrency'] : SKIP
      unit_price_in_invoice_currency =
        hash.key?('UnitPriceInInvoiceCurrency') ? hash['UnitPriceInInvoiceCurrency'] : SKIP
      unit_discount_transaction_currency =
        hash.key?('UnitDiscountTransactionCurrency') ? hash['UnitDiscountTransactionCurrency'] : SKIP
      unit_discount_invoice_currency =
        hash.key?('UnitDiscountInvoiceCurrency') ? hash['UnitDiscountInvoiceCurrency'] : SKIP
      is_invoiced = hash.key?('IsInvoiced') ? hash['IsInvoiced'] : SKIP
      invoice_number = hash.key?('InvoiceNumber') ? hash['InvoiceNumber'] : SKIP
      invoice_date = hash.key?('InvoiceDate') ? hash['InvoiceDate'] : SKIP
      site_code = hash.key?('SiteCode') ? hash['SiteCode'] : SKIP
      site_name = hash.key?('SiteName') ? hash['SiteName'] : SKIP
      site_country = hash.key?('SiteCountry') ? hash['SiteCountry'] : SKIP
      location = ExceptionSiteLocation.from_hash(hash['Location']) if hash['Location']
      card_group_name =
        hash.key?('CardGroupName') ? hash['CardGroupName'] : SKIP
      receipt_number = hash.key?('ReceiptNumber') ? hash['ReceiptNumber'] : SKIP
      product_code = hash.key?('ProductCode') ? hash['ProductCode'] : SKIP
      product_name = hash.key?('ProductName') ? hash['ProductName'] : SKIP
      product_group_id =
        hash.key?('ProductGroupId') ? hash['ProductGroupId'] : SKIP
      product_group_name =
        hash.key?('ProductGroupName') ? hash['ProductGroupName'] : SKIP
      del_co_exchange_rate =
        hash.key?('DelCoExchangeRate') ? hash['DelCoExchangeRate'] : SKIP
      col_co_exchange_rate =
        hash.key?('ColCoExchangeRate') ? hash['ColCoExchangeRate'] : SKIP
      is_shell_site = hash.key?('IsShellSite') ? hash['IsShellSite'] : SKIP
      network = hash.key?('Network') ? hash['Network'] : SKIP
      site_group_id = hash.key?('SiteGroupId') ? hash['SiteGroupId'] : SKIP
      site_group_name =
        hash.key?('SiteGroupName') ? hash['SiteGroupName'] : SKIP
      posting_date = hash.key?('PostingDate') ? hash['PostingDate'] : SKIP
      issuer_code = hash.key?('IssuerCode') ? hash['IssuerCode'] : SKIP
      purchased_in_country_code =
        hash.key?('PurchasedInCountryCode') ? hash['PurchasedInCountryCode'] : SKIP
      customer_country_code =
        hash.key?('CustomerCountryCode') ? hash['CustomerCountryCode'] : SKIP
      customer_country =
        hash.key?('CustomerCountry') ? hash['CustomerCountry'] : SKIP
      release_code = hash.key?('ReleaseCode') ? hash['ReleaseCode'] : SKIP
      card_group_id = hash.key?('CardGroupId') ? hash['CardGroupId'] : SKIP
      card_sequence_number =
        hash.key?('CardSequenceNumber') ? hash['CardSequenceNumber'] : SKIP
      check_digit = hash.key?('CheckDigit') ? hash['CheckDigit'] : SKIP
      fleet_id_description =
        hash.key?('FleetIDDescription') ? hash['FleetIDDescription'] : SKIP
      vat_rate = hash.key?('VATRate') ? hash['VATRate'] : SKIP
      vat_category = hash.key?('VATCategory') ? hash['VATCategory'] : SKIP
      effective_discount_in_trx_currency =
        hash.key?('EffectiveDiscountInTrxCurrency') ? hash['EffectiveDiscountInTrxCurrency'] : SKIP
      transaction_type =
        hash.key?('TransactionType') ? hash['TransactionType'] : SKIP
      pin_indicator = hash.key?('PINIndicator') ? hash['PINIndicator'] : SKIP
      vat_applicable = hash.key?('VATApplicable') ? hash['VATApplicable'] : SKIP
      net_invoice_indicator =
        hash.key?('NetInvoiceIndicator') ? hash['NetInvoiceIndicator'] : SKIP
      customer_currency_code =
        hash.key?('CustomerCurrencyCode') ? hash['CustomerCurrencyCode'] : SKIP
      customer_currency_symbol =
        hash.key?('CustomerCurrencySymbol') ? hash['CustomerCurrencySymbol'] : SKIP
      effective_unit_discount_in_customer_currency =
        hash.key?('EffectiveUnitDiscountInCustomerCurrency') ? hash['EffectiveUnitDiscountInCustomerCurrency'] : SKIP
      effective_discount_in_customer_currency =
        hash.key?('EffectiveDiscountInCustomerCurrency') ? hash['EffectiveDiscountInCustomerCurrency'] : SKIP
      va_ton_net_amount_in_customer_currency =
        hash.key?('VATonNetAmountInCustomerCurrency') ? hash['VATonNetAmountInCustomerCurrency'] : SKIP
      discount_type = hash.key?('DiscountType') ? hash['DiscountType'] : SKIP
      transaction_status =
        hash.key?('TransactionStatus') ? hash['TransactionStatus'] : SKIP
      payer_group = hash.key?('PayerGroup') ? hash['PayerGroup'] : SKIP
      refund_flag = hash.key?('RefundFlag') ? hash['RefundFlag'] : SKIP
      original_sales_item_id =
        hash.key?('OriginalSalesItemId') ? hash['OriginalSalesItemId'] : SKIP
      delco_name = hash.key?('DelcoName') ? hash['DelcoName'] : SKIP
      delco_code = hash.key?('DelcoCode') ? hash['DelcoCode'] : SKIP
      payer_number = hash.key?('PayerNumber') ? hash['PayerNumber'] : SKIP
      payer_name = hash.key?('PayerName') ? hash['PayerName'] : SKIP
      card_expiry_period =
        hash.key?('CardExpiryPeriod') ? hash['CardExpiryPeriod'] : SKIP
      authorisation_code =
        hash.key?('AuthorisationCode') ? hash['AuthorisationCode'] : SKIP
      transaction_id = hash.key?('TransactionId') ? hash['TransactionId'] : SKIP
      transaction_line =
        hash.key?('TransactionLine') ? hash['TransactionLine'] : SKIP
      allow_clearing = hash.key?('AllowClearing') ? hash['AllowClearing'] : SKIP
      crm_number = hash.key?('CRMNumber') ? hash['CRMNumber'] : SKIP
      dispute_status = hash.key?('DisputeStatus') ? hash['DisputeStatus'] : SKIP
      rebate_rate = hash.key?('RebateRate') ? hash['RebateRate'] : SKIP
      del_co_to_col_co_exchange_rate =
        hash.key?('DelCoToColCoExchangeRate') ? hash['DelCoToColCoExchangeRate'] : SKIP
      net_euro_amount =
        hash.key?('NetEuroAmount') ? hash['NetEuroAmount'] : SKIP
      euro_rebate_amount =
        hash.key?('EuroRebateAmount') ? hash['EuroRebateAmount'] : SKIP
      euro_vat_amount =
        hash.key?('EuroVATAmount') ? hash['EuroVATAmount'] : SKIP
      parent_customer_number =
        hash.key?('ParentCustomerNumber') ? hash['ParentCustomerNumber'] : SKIP
      va_ton_net_amount =
        hash.key?('VATonNetAmount') ? hash['VATonNetAmount'] : SKIP
      vat_country = hash.key?('VATCountry') ? hash['VATCountry'] : SKIP

      # Create object from extracted values.
      TransactionExceptions.new(sales_item_id,
                                card_id,
                                product_id,
                                transaction_guid,
                                transaction_date,
                                customer_invoice_value_total_gross,
                                card_pan,
                                card_expiry,
                                transaction_time,
                                utc_offset,
                                fleet_id_input,
                                odometer_input,
                                driver_name,
                                vehicle_registration,
                                invoice_currency_code,
                                invoice_currency_symbol,
                                transaction_currency_code,
                                transaction_currency_symbol,
                                transaction_net_amount,
                                transaction_tax,
                                transaction_gross_amount,
                                invoice_net_amount,
                                invoice_tax,
                                invoice_gross_amount,
                                purchased_in_country,
                                account_id,
                                account_number,
                                account_name,
                                account_short_name,
                                quantity,
                                fuel_product,
                                unit_price_in_transaction_currency,
                                unit_price_in_invoice_currency,
                                unit_discount_transaction_currency,
                                unit_discount_invoice_currency,
                                is_invoiced,
                                invoice_number,
                                invoice_date,
                                site_code,
                                site_name,
                                site_country,
                                location,
                                card_group_name,
                                receipt_number,
                                product_code,
                                product_name,
                                product_group_id,
                                product_group_name,
                                del_co_exchange_rate,
                                col_co_exchange_rate,
                                is_shell_site,
                                network,
                                site_group_id,
                                site_group_name,
                                posting_date,
                                issuer_code,
                                purchased_in_country_code,
                                customer_country_code,
                                customer_country,
                                release_code,
                                card_group_id,
                                card_sequence_number,
                                check_digit,
                                fleet_id_description,
                                vat_rate,
                                vat_category,
                                effective_discount_in_trx_currency,
                                transaction_type,
                                pin_indicator,
                                vat_applicable,
                                net_invoice_indicator,
                                customer_currency_code,
                                customer_currency_symbol,
                                effective_unit_discount_in_customer_currency,
                                effective_discount_in_customer_currency,
                                va_ton_net_amount_in_customer_currency,
                                discount_type,
                                transaction_status,
                                payer_group,
                                refund_flag,
                                original_sales_item_id,
                                delco_name,
                                delco_code,
                                payer_number,
                                payer_name,
                                card_expiry_period,
                                authorisation_code,
                                transaction_id,
                                transaction_line,
                                allow_clearing,
                                crm_number,
                                dispute_status,
                                rebate_rate,
                                del_co_to_col_co_exchange_rate,
                                net_euro_amount,
                                euro_rebate_amount,
                                euro_vat_amount,
                                parent_customer_number,
                                va_ton_net_amount,
                                vat_country)
    end
  end
end
