# shell_data_reporting_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellDataReportingApIs
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
