# shell_data_reporting_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require 'date'
require 'json'

require 'apimatic_core_interfaces'
require 'apimatic_core'
require 'apimatic_faraday_client_adapter'

require_relative 'shell_data_reporting_ap_is/api_helper'
require_relative 'shell_data_reporting_ap_is/client'

# Utilities
require_relative 'shell_data_reporting_ap_is/utilities/file_wrapper'
require_relative 'shell_data_reporting_ap_is/utilities/date_time_helper'
require_relative 'shell_data_reporting_ap_is/utilities/union_type_lookup'

# Http
require_relative 'shell_data_reporting_ap_is/http/http_call_back'
require_relative 'shell_data_reporting_ap_is/http/http_method_enum'
require_relative 'shell_data_reporting_ap_is/http/http_request'
require_relative 'shell_data_reporting_ap_is/http/http_response'
require_relative 'shell_data_reporting_ap_is/http/proxy_settings'


require_relative 'shell_data_reporting_ap_is/http/auth/o_auth2'

# Models
require_relative 'shell_data_reporting_ap_is/models/base_model'
require_relative 'shell_data_reporting_ap_is/models/logged_in_user_res'
require_relative 'shell_data_reporting_ap_is/models/logged_in_user_response'
require_relative 'shell_data_reporting_ap_is/models/role'
require_relative 'shell_data_reporting_ap_is/models/payer_access'
require_relative 'shell_data_reporting_ap_is/models/account_access'
require_relative 'shell_data_reporting_ap_is/models/col_co_access'
require_relative 'shell_data_reporting_ap_is/models/eid_access'
require_relative 'shell_data_reporting_ap_is/models/payer_req'
require_relative 'shell_data_reporting_ap_is/models/payer_request'
require_relative 'shell_data_reporting_ap_is/models/payers'
require_relative 'shell_data_reporting_ap_is/models/payer_res'
require_relative 'shell_data_reporting_ap_is/models/payer_details'
require_relative 'shell_data_reporting_ap_is/models/invoice_distribution_method'
require_relative 'shell_data_reporting_ap_is/models/bank_account'
require_relative 'shell_data_reporting_ap_is/models/address'
require_relative 'shell_data_reporting_ap_is/models/customer_contract'
require_relative 'shell_data_reporting_ap_is/models/customer_req'
require_relative 'shell_data_reporting_ap_is/models/customer_detail_request'
require_relative 'shell_data_reporting_ap_is/models/customer_res'
require_relative 'shell_data_reporting_ap_is/models/customer_detail_response'
require_relative 'shell_data_reporting_ap_is/models/delivery_addresses'
require_relative 'shell_data_reporting_ap_is/models/pin_advice_types'
require_relative 'shell_data_reporting_ap_is/models/account_req'
require_relative 'shell_data_reporting_ap_is/models/account_request'
require_relative 'shell_data_reporting_ap_is/models/accounts'
require_relative 'shell_data_reporting_ap_is/models/account_res'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'account_response_accounts_items'
require_relative 'shell_data_reporting_ap_is/models/card_type_req'
require_relative 'shell_data_reporting_ap_is/models/card_type_request'
require_relative 'shell_data_reporting_ap_is/models/card_type_res'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'card_type_response_customer_card_types_items'
require_relative 'shell_data_reporting_ap_is/models/card_day_time_restrictions'
require_relative 'shell_data_reporting_ap_is/models/purchase_categories'
require_relative 'shell_data_reporting_ap_is/models/card_usage_restrictions'
require_relative 'shell_data_reporting_ap_is/models/card_group_req'
require_relative 'shell_data_reporting_ap_is/models/card_group_request'
require_relative 'shell_data_reporting_ap_is/models/card_group_res'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'card_group_response_card_groups_items'
require_relative 'shell_data_reporting_ap_is/models/audit_req'
require_relative 'shell_data_reporting_ap_is/models/audit_request'
require_relative 'shell_data_reporting_ap_is/models/audit_response'
require_relative 'shell_data_reporting_ap_is/models/audit_array_elements'
require_relative 'shell_data_reporting_ap_is/models/audit_response_audits_items'
require_relative 'shell_data_reporting_ap_is/models/finance_currency2'
require_relative 'shell_data_reporting_ap_is/models/logged_in_user_req'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'fleetmanagement_v1_user_loggedinuser_request'
require_relative 'shell_data_reporting_ap_is/models/customer_price_list_req'
require_relative 'shell_data_reporting_ap_is/models/customer_price_list_request'
require_relative 'shell_data_reporting_ap_is/models/customer_price_list_res'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'customer_price_list_response'
require_relative 'shell_data_reporting_ap_is/models/price_list'
require_relative 'shell_data_reporting_ap_is/models/tier'
require_relative 'shell_data_reporting_ap_is/models/price_transaction_req'
require_relative 'shell_data_reporting_ap_is/models/price_transaction_request'
require_relative 'shell_data_reporting_ap_is/models/priced_transaction_res'
require_relative 'shell_data_reporting_ap_is/models/priced_transaction_response'
require_relative 'shell_data_reporting_ap_is/models/price_trans_summary_req'
require_relative 'shell_data_reporting_ap_is/models/price_trans_summary_request'
require_relative 'shell_data_reporting_ap_is/models/priced_trans_summary_resp'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'multi_priced_transaction_req'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'multi_priced_transaction_request'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'multi_priced_transaction_res'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'multi_priced_transaction_response'
require_relative 'shell_data_reporting_ap_is/models/site_location'
require_relative 'shell_data_reporting_ap_is/models/card_usage_summary_req'
require_relative 'shell_data_reporting_ap_is/models/card_usage_summary_request'
require_relative 'shell_data_reporting_ap_is/models/card_usage_summary_res'
require_relative 'shell_data_reporting_ap_is/models/card_usage_summary_response'
require_relative 'shell_data_reporting_ap_is/models/usage_summary'
require_relative 'shell_data_reporting_ap_is/models/volume_based_bonus_req'
require_relative 'shell_data_reporting_ap_is/models/volume_based_bonus_request'
require_relative 'shell_data_reporting_ap_is/models/volume_based_bonus_res'
require_relative 'shell_data_reporting_ap_is/models/volume_based_bonus_response'
require_relative 'shell_data_reporting_ap_is/models/bonus_configuration'
require_relative 'shell_data_reporting_ap_is/models/fee_rule_location'
require_relative 'shell_data_reporting_ap_is/models/fee_rule_tier'
require_relative 'shell_data_reporting_ap_is/models/associated_account'
require_relative 'shell_data_reporting_ap_is/models/fee_rule_product'
require_relative 'shell_data_reporting_ap_is/models/current_volume'
require_relative 'shell_data_reporting_ap_is/models/bonus_history'
require_relative 'shell_data_reporting_ap_is/models/volume_based_pricing_req'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'volume_based_pricing_request'
require_relative 'shell_data_reporting_ap_is/models/volume_based_pricing_res'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'volume_based_pricing_response'
require_relative 'shell_data_reporting_ap_is/models/pricing_current_volume'
require_relative 'shell_data_reporting_ap_is/models/pricing_history'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'transaction_fees_summary_req'
require_relative 'shell_data_reporting_ap_is/models/transaction_fees_req'
require_relative 'shell_data_reporting_ap_is/models/transaction_fees_request'
require_relative 'shell_data_reporting_ap_is/models/transaction_fees_res'
require_relative 'shell_data_reporting_ap_is/models/fee_item'
require_relative 'shell_data_reporting_ap_is/models/fees_fee_rule_tiers'
require_relative 'shell_data_reporting_ap_is/models/fee_summary_response'
require_relative 'shell_data_reporting_ap_is/models/fee_item_summary_all_of0'
require_relative 'shell_data_reporting_ap_is/models/fuel_consumption_req'
require_relative 'shell_data_reporting_ap_is/models/fuel_consumption_request'
require_relative 'shell_data_reporting_ap_is/models/fuel_consumption_card'
require_relative 'shell_data_reporting_ap_is/models/fuel_consumption_response'
require_relative 'shell_data_reporting_ap_is/models/fuel_consumption_data'
require_relative 'shell_data_reporting_ap_is/models/update_odometer_request'
require_relative 'shell_data_reporting_ap_is/models/update_odometer'
require_relative 'shell_data_reporting_ap_is/models/update_odometer_resp'
require_relative 'shell_data_reporting_ap_is/models/update_odometer_response'
require_relative 'shell_data_reporting_ap_is/models/update_odometer_reference'
require_relative 'shell_data_reporting_ap_is/models/transaction_exceptions_req'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'transaction_exceptions_request'
require_relative 'shell_data_reporting_ap_is/models/exception_product'
require_relative 'shell_data_reporting_ap_is/models/transaction_exceptions_res'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'transaction_exceptions_response'
require_relative 'shell_data_reporting_ap_is/models/card_exceptions'
require_relative 'shell_data_reporting_ap_is/models/transaction_exceptions'
require_relative 'shell_data_reporting_ap_is/models/exception_site_location'
require_relative 'shell_data_reporting_ap_is/models/recent_transaction_request'
require_relative 'shell_data_reporting_ap_is/models/recent_transaction_req'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'recent_transactions_response'
require_relative 'shell_data_reporting_ap_is/models/recent_transactions'
require_relative 'shell_data_reporting_ap_is/models/error_object'
require_relative 'shell_data_reporting_ap_is/models/error_details'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'priced_transaction_request_v2'
require_relative 'shell_data_reporting_ap_is/models/priced_request_data'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'priced_transaction_response_v2'
require_relative 'shell_data_reporting_ap_is/models/priced_response_data'
require_relative 'shell_data_reporting_ap_is/models/invoice_search_request'
require_relative 'shell_data_reporting_ap_is/models/invoice_search_response'
require_relative 'shell_data_reporting_ap_is/models/invoice_search_details'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'invoice_search_additional_document'
require_relative 'shell_data_reporting_ap_is/models/invoice_summary_request'
require_relative 'shell_data_reporting_ap_is/models/invoice_summary_response'
require_relative 'shell_data_reporting_ap_is/models/invoice_summary_details'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'statement_of_account_request'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'statement_of_account_response'
require_relative 'shell_data_reporting_ap_is/models/statement_of_account_resp'
require_relative 'shell_data_reporting_ap_is/models/last_statement_of_account'
require_relative 'shell_data_reporting_ap_is/models/monthly_invoice_trend'
require_relative 'shell_data_reporting_ap_is/models/past_statement_of_accounts'
require_relative 'shell_data_reporting_ap_is/models/payments_since_last_soa'
require_relative 'shell_data_reporting_ap_is/models/invoices_summaries'
require_relative 'shell_data_reporting_ap_is/models/invoice_dates_request'
require_relative 'shell_data_reporting_ap_is/models/invoice_dates_response_data'
require_relative 'shell_data_reporting_ap_is/models/invoice_dates_data'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'search_statement_of_account_request'
require_relative 'shell_data_reporting_ap_is/models/search_soa_req'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'search_statement_of_account_response'
require_relative 'shell_data_reporting_ap_is/models/search_statement_of_account'
require_relative 'shell_data_reporting_ap_is/models/search_documents_request'
require_relative 'shell_data_reporting_ap_is/models/search_doc_req'
require_relative 'shell_data_reporting_ap_is/models/search_documents_response'
require_relative 'shell_data_reporting_ap_is/models/search_documents_invoice'
require_relative 'shell_data_reporting_ap_is/models/eid_search_request'
require_relative 'shell_data_reporting_ap_is/models/eid_search_req'
require_relative 'shell_data_reporting_ap_is/models/eid_document_response'
require_relative 'shell_data_reporting_ap_is/models/eid_document'
require_relative 'shell_data_reporting_ap_is/models/invoice_download_request'
require_relative 'shell_data_reporting_ap_is/models/invoice_download_req'
require_relative 'shell_data_reporting_ap_is/models/eid_download_request'
require_relative 'shell_data_reporting_ap_is/models/eid_download_req'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'priced_transaction_response_transactions_items'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'priced_transaction_items_location_items'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'priced_trans_summary_response_transactions_summary_items'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'multi_priced_transaction_request_accounts_items'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'multi_priced_transaction_response_transactions_items'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'invoice_search_request_filters'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'invoice_summary_request_filters'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'statement_of_account_request_filters'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'invoice_dates_request_filters'
require_relative 'shell_data_reporting_ap_is/models/filters'
require_relative 'shell_data_reporting_ap_is/models/last_statement_of_account2'
require_relative 'shell_data_reporting_ap_is/models/location'
require_relative 'shell_data_reporting_ap_is/models/warning'
require_relative 'shell_data_reporting_ap_is/models/cart_type_account'
require_relative 'shell_data_reporting_ap_is/models/o_auth_token'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'priced_transaction_req_v2_invoice_status_enum'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'priced_transaction_req_v2_sort_order_enum'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'priced_transaction_req_v2_period_enum'
require_relative 'shell_data_reporting_ap_is/models/' \
                 'priced_transaction_resp_v2_refund_flag_enum'
require_relative 'shell_data_reporting_ap_is/models/o_auth_provider_error_enum'

# Exceptions
require_relative 'shell_data_reporting_ap_is/exceptions/api_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_accounts400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_accounts401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_accounts403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_accounts404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_accounts500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_auditreport400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_auditreport401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_auditreport403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_auditreport404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_auditreport500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_cardgroups400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_cardgroups401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_cardgroups403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_cardgroups404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_cardgroups500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_customer400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_customer401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_customer403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_customer404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_customer500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_payers400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_payers401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_payers403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_payers404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_payers500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_pricelist400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_pricelist401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_pricelist403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_pricelist404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v1_pricelist500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v2_cardtype400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v2_cardtype401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v2_cardtype403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v2_cardtype404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'customer_management_v2_cardtype500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_dates400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_dates401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_dates403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_dates404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_dates500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_download400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_download401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_download403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_download404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_download500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_eiddownload400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_eiddownload401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_eiddownload403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_eiddownload404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_eiddownload500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_eidsearch400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_eidsearch401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_eidsearch403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_eidsearch404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_eidsearch500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_search400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_search401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_search403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_search404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_search500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_searchdocuments400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_searchdocuments401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_searchdocuments403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_searchdocuments404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_searchdocuments500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_searchstatemento' \
                 'faccount400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_searchstatemento' \
                 'faccount401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_searchstatemento' \
                 'faccount403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_searchstatemento' \
                 'faccount404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_searchstatemento' \
                 'faccount500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_statementofaccount400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_statementofaccount401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_statementofaccount403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_statementofaccount404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_statementofaccount500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_summary400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_summary401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_summary403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_summary404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'invoice_management_v1_summary500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_cardusagesummary400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_cardusagesummary401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_cardusagesummary403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_cardusagesummary404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_cardusagesummary500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_exceptions400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_exceptions401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_exceptions403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_exceptions404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_exceptions500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_fees400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_fees401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_fees403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_fees404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_fees500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_feessummary400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_feessummary401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_feessummary403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_feessummary404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_feessummary500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_fuelconsumption400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_fuelconsumption401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_fuelconsumption403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_fuelconsumption404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_fuelconsumption500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_multipayerspricedt' \
                 'ransactions400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_multipayerspricedt' \
                 'ransactions401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_multipayerspricedt' \
                 'ransactions403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_multipayerspricedt' \
                 'ransactions404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_multipayerspricedt' \
                 'ransactions500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_priced400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_priced401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_priced403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_priced404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_priced500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_pricedtransaction400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_pricedtransaction401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_pricedtransaction403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_pricedtransaction404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_pricedtransaction500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_pricedtransactions' \
                 'summary400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_pricedtransactions' \
                 'summary401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_pricedtransactions' \
                 'summary403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_pricedtransactions' \
                 'summary404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_pricedtransactions' \
                 'summary500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_recent400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_recent401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_recent403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_recent404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_recent500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_updateodometer400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_updateodometer401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_updateodometer403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_updateodometer404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_updateodometer500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_volumebasedbonus400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_volumebasedbonus401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_volumebasedbonus403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_volumebasedbonus404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_volumebasedbonus500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_volumebasedpricing400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_volumebasedpricing401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_volumebasedpricing403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_volumebasedpricing404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'transaction_data_v1_volumebasedpricing500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'user_management_v1_loggedinuser400_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'user_management_v1_loggedinuser401_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'user_management_v1_loggedinuser403_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'user_management_v1_loggedinuser404_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'user_management_v1_loggedinuser500_error_exception'
require_relative 'shell_data_reporting_ap_is/exceptions/' \
                 'o_auth_provider_exception'

require_relative 'shell_data_reporting_ap_is/configuration'

# Controllers
require_relative 'shell_data_reporting_ap_is/controllers/base_controller'
require_relative 'shell_data_reporting_ap_is/controllers/customer_controller'
require_relative 'shell_data_reporting_ap_is/controllers/transaction_controller'
require_relative 'shell_data_reporting_ap_is/controllers/invoice_controller'
require_relative 'shell_data_reporting_ap_is/controllers/' \
                 'o_auth_authorization_controller'
